apiVersion: v1
kind: ConfigMap
metadata:
  name: lobby-frontend-config
  namespace: playhub
  labels: { env: production }
data:
  REACT_APP_ENV: production
  REACT_APP_API_BASE_URL: "https://api.playhub.com"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lobby-frontend
  namespace: playhub
  labels: { app: lobby-frontend }
spec:
  replicas: 3
  selector: { matchLabels: { app: lobby-frontend } }
  template:
    metadata:
      labels: { app: lobby-frontend }
    spec:
      containers:
        - name: frontend
          image: docker.io/scruffyprodigy/playhub-frontend:production
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: lobby-frontend-config
                  key: REACT_APP_ENV
            - name: REACT_APP_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: lobby-frontend-config
                  key: REACT_APP_API_BASE_URL
          readinessProbe:
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 5
          livenessProbe:
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 10
          resources:
            requests: { cpu: "500m", memory: "512Mi" }
            limits:   { cpu: "2000m", memory: "2Gi" }
