apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init
  namespace: playhub
data:
  0001_initial.sql: |
    create extension if not exists "uuid-ossp";
    create extension if not exists citext;

    create table if not exists users (
      id uuid primary key default uuid_generate_v4(),
      email citext unique not null,
      created_at timestamptz not null default now()
    );

    create table if not exists login_tokens (
      token uuid primary key default uuid_generate_v4(),
      email citext not null,
      expires_at timestamptz not null,
      used_at timestamptz
    );

    create table if not exists games (
      id uuid primary key default uuid_generate_v4(),
      name text not null
    );

    create table if not exists game_sessions (
      id uuid primary key default uuid_generate_v4(),
      game_id uuid not null references games(id),
      status text not null default 'pending',
      created_at timestamptz default now()
    );

    create table if not exists session_players (
      session_id uuid references game_sessions(id) on delete cascade,
      user_id uuid references users(id) on delete cascade,
      role text default 'player',
      joined_at timestamptz default now(),
      primary key (session_id, user_id)
    );

    create table if not exists match_queue (
      id bigserial primary key,
      game_id uuid not null references games(id),
      user_id uuid not null references users(id),
      enqueued_at timestamptz not null default now(),
      unique (game_id, user_id)
    );
    create index if not exists match_queue_game_time_idx on match_queue (game_id, enqueued_at);
