ALTER TABLE games
    ADD COLUMN IF NOT EXISTS game_mode VARCHAR(50) DEFAULT 'duel',
    ADD COLUMN IF NOT EXISTS min_players INTEGER DEFAULT 1,
    ADD COLUMN IF NOT EXISTS max_players INTEGER DEFAULT 2;

ALTER TABLE game_modes
    ADD COLUMN IF NOT EXISTS best_of INTEGER;
