// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type ActiveQueue struct {
	QueueID     string      `json:"queueId"`
	GameID      string      `json:"gameId"`
	GameName    string      `json:"gameName"`
	Status      QueueStatus `json:"status"`
	QueuedCount *int        `json:"queuedCount,omitempty"`
	QueuePath   *string     `json:"queuePath,omitempty"`
	// Human label for queuePath from the mode seatTemplate (e.g. Clue Giver).
	QueuePathDisplayName *string `json:"queuePathDisplayName,omitempty"`
	JoinURL              *string `json:"joinUrl,omitempty"`
}

type DigitalGood struct {
	ID          string  `json:"id"`
	Code        string  `json:"code"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Game        *Game   `json:"game,omitempty"`
}

type Entitlement struct {
	Good      *DigitalGood `json:"good"`
	Quantity  int          `json:"quantity"`
	GrantedAt time.Time    `json:"grantedAt"`
}

type Game struct {
	ID               string      `json:"id"`
	Name             string      `json:"name"`
	CreatedAt        time.Time   `json:"createdAt"`
	ActiveSessions   []*Session  `json:"activeSessions"`
	Slug             *string     `json:"slug,omitempty"`
	PlayURL          *string     `json:"playUrl,omitempty"`
	APIBaseURL       *string     `json:"apiBaseUrl,omitempty"`
	ManifestSyncedAt *time.Time  `json:"manifestSyncedAt,omitempty"`
	ManifestHash     *string     `json:"manifestHash,omitempty"`
	GameVersion      *string     `json:"gameVersion,omitempty"`
	Modes            []*GameMode `json:"modes"`
}

type GameMode struct {
	ID          string          `json:"id"`
	ModeKey     string          `json:"modeKey"`
	DisplayName string          `json:"displayName"`
	MinPlayers  int             `json:"minPlayers"`
	MaxPlayers  int             `json:"maxPlayers"`
	Status      string          `json:"status"`
	Seats       []*GameModeSeat `json:"seats"`
	// Join options with human labels and per-cohort fire sizes.
	QueuePaths []*GameModeQueuePath `json:"queuePaths"`
	Queues     []*ModeQueue         `json:"queues"`
}

// One join bucket from seatTemplate (composition modes).
type GameModeQueuePath struct {
	QueuePath      string `json:"queuePath"`
	DisplayName    string `json:"displayName"`
	MinPlayers     int    `json:"minPlayers"`
	MaxPlayers     int    `json:"maxPlayers"`
	PlayersToStart int    `json:"playersToStart"`
}

type GameModeSeat struct {
	SeatKey string  `json:"seatKey"`
	Team    *string `json:"team,omitempty"`
	Role    *string `json:"role,omitempty"`
	// Lobby join bucket derived from seatTemplate (empty for fifo modes).
	QueuePath *string `json:"queuePath,omitempty"`
	SortOrder int     `json:"sortOrder"`
}

type JoinResult struct {
	Queued      bool    `json:"queued"`
	SessionID   *string `json:"sessionId,omitempty"`
	JoinURL     *string `json:"joinUrl,omitempty"`
	QueuedCount *int    `json:"queuedCount,omitempty"`
	QueuePath   *string `json:"queuePath,omitempty"`
	Message     *string `json:"message,omitempty"`
}

type ModeQueue struct {
	ID             string `json:"id"`
	Name           string `json:"name"`
	PlayersToStart int    `json:"playersToStart"`
	Status         string `json:"status"`
	WaitingCount   int    `json:"waitingCount"`
}

type Mutation struct {
}

type MyTableSeat struct {
	TableID         string `json:"tableId"`
	RoomID          string `json:"roomId"`
	InviteCode      string `json:"inviteCode"`
	GameID          string `json:"gameId"`
	GameName        string `json:"gameName"`
	ModeID          string `json:"modeId"`
	ModeName        string `json:"modeName"`
	SeatKey         string `json:"seatKey"`
	SeatDisplayName string `json:"seatDisplayName"`
}

type PublicPlayer struct {
	ID           string        `json:"id"`
	DisplayName  *string       `json:"displayName,omitempty"`
	AvatarURL    *string       `json:"avatarUrl,omitempty"`
	AvatarSource *AvatarSource `json:"avatarSource,omitempty"`
}

type Query struct {
}

type QueueUpdate struct {
	GameID      string      `json:"gameId"`
	QueueID     string      `json:"queueId"`
	Status      QueueStatus `json:"status"`
	SessionID   *string     `json:"sessionId,omitempty"`
	JoinURL     *string     `json:"joinUrl,omitempty"`
	QueuedCount int         `json:"queuedCount"`
	Message     *string     `json:"message,omitempty"`
}

type RegisterGameInput struct {
	Slug        string  `json:"slug"`
	PlayURL     string  `json:"playUrl"`
	APIBaseURL  string  `json:"apiBaseUrl"`
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
}

type RegisterGamePayload struct {
	Game          *Game  `json:"game"`
	WebhookSecret string `json:"webhookSecret"`
	// Per-game credential for provision + player GraphQL (derived from game id).
	ServiceToken string `json:"serviceToken"`
}

type ReturnDestination struct {
	Path string `json:"path"`
	Kind string `json:"kind"`
}

type Room struct {
	ID         string         `json:"id"`
	InviteCode string         `json:"inviteCode"`
	JoinURL    string         `json:"joinUrl"`
	Host       *User          `json:"host"`
	Members    []*User        `json:"members"`
	Messages   []*RoomMessage `json:"messages"`
	Tables     []*Table       `json:"tables"`
}

type RoomMessage struct {
	ID        string    `json:"id"`
	Author    *User     `json:"author"`
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"createdAt"`
}

type Session struct {
	ID        string        `json:"id"`
	Game      *Game         `json:"game"`
	Status    SessionStatus `json:"status"`
	CreatedAt time.Time     `json:"createdAt"`
	Players   []*User       `json:"players"`
}

type SpiritAnimalAnswer struct {
	ID    string `json:"id"`
	Label string `json:"label"`
}

type SpiritAnimalCardQuestion struct {
	Slot                 string                `json:"slot"`
	SlotName             string                `json:"slotName"`
	Card                 string                `json:"card"`
	CardMeaningInGeneral string                `json:"cardMeaningInGeneral"`
	CardMeaningForSlot   string                `json:"cardMeaningForSlot"`
	Question             string                `json:"question"`
	Answers              []*SpiritAnimalAnswer `json:"answers"`
}

type SpiritAnimalJourneyEligibility struct {
	CanBegin       bool       `json:"canBegin"`
	CooldownEndsAt *time.Time `json:"cooldownEndsAt,omitempty"`
	DaysRemaining  *int       `json:"daysRemaining,omitempty"`
}

type SpiritAnimalJourneySummary struct {
	Compass  string `json:"compass"`
	Coin     string `json:"coin"`
	Storm    string `json:"storm"`
	Campfire string `json:"campfire"`
	Beacon   string `json:"beacon"`
}

type SpiritAnimalPersonality struct {
	Overview       string                      `json:"overview"`
	JourneySummary *SpiritAnimalJourneySummary `json:"journeySummary"`
	CoreThemes     []string                    `json:"coreThemes"`
	Strengths      []string                    `json:"strengths"`
	Tensions       []string                    `json:"tensions"`
	SocialIdentity string                      `json:"socialIdentity"`
}

type SpiritAnimalReading struct {
	ID                string                      `json:"id"`
	Status            SpiritAnimalReadingStatus   `json:"status"`
	Draw              []int                       `json:"draw"`
	CardQuestions     []*SpiritAnimalCardQuestion `json:"cardQuestions,omitempty"`
	Personality       *SpiritAnimalPersonality    `json:"personality,omitempty"`
	MascotOverview    *string                     `json:"mascotOverview,omitempty"`
	Totems            []*SpiritAnimalTotem        `json:"totems,omitempty"`
	SelectedTotemName *string                     `json:"selectedTotemName,omitempty"`
	ErrorMessage      *string                     `json:"errorMessage,omitempty"`
	ImagesMissing     bool                        `json:"imagesMissing"`
	// When status is GENERATING_QUESTIONS or PROCESSING, when the current wait began.
	PhaseStartedAt *time.Time `json:"phaseStartedAt,omitempty"`
	// Approximate total seconds for the current processing phase, based on recent readings.
	EstimatedPhaseSeconds *int `json:"estimatedPhaseSeconds,omitempty"`
}

type SpiritAnimalTotem struct {
	Name                    string   `json:"name"`
	Animal                  string   `json:"animal"`
	SocialArchetype         string   `json:"socialArchetype"`
	CoreConcept             string   `json:"coreConcept"`
	ColorPalette            []string `json:"colorPalette"`
	PersonalitySummary      string   `json:"personalitySummary"`
	WhyThisAnimal           string   `json:"whyThisAnimal"`
	OriginStory             string   `json:"originStory"`
	ImageURL                *string  `json:"imageUrl,omitempty"`
	FitScore                *int     `json:"fitScore,omitempty"`
	Affinity                *string  `json:"affinity,omitempty"`
	ReadingEmphasis         *string  `json:"readingEmphasis,omitempty"`
	WhyThisAnimalMakesSense *string  `json:"whyThisAnimalMakesSense,omitempty"`
	WhyChooseThisAvatar     *string  `json:"whyChooseThisAvatar,omitempty"`
}

type StarterAvatar struct {
	Key      string `json:"key"`
	Name     string `json:"name"`
	Slot     string `json:"slot"`
	ImageURL string `json:"imageUrl"`
}

type Subscription struct {
}

type Table struct {
	ID                  string                     `json:"id"`
	Game                *Game                      `json:"game"`
	Mode                *GameMode                  `json:"mode"`
	CreatedAt           time.Time                  `json:"createdAt"`
	King                *User                      `json:"king,omitempty"`
	Seats               []*TableSeat               `json:"seats"`
	SeatSlots           []*TableSeatSlot           `json:"seatSlots"`
	CanStart            bool                       `json:"canStart"`
	CanDiscard          bool                       `json:"canDiscard"`
	LookForGroupOptions []*TableLookForGroupOption `json:"lookForGroupOptions"`
}

type TableLookForGroupOption struct {
	QueueID   string `json:"queueId"`
	QueueName string `json:"queueName"`
	Visible   bool   `json:"visible"`
	Enabled   bool   `json:"enabled"`
}

type TableSeat struct {
	SeatKey  string    `json:"seatKey"`
	User     *User     `json:"user"`
	SeatedAt time.Time `json:"seatedAt"`
}

type TableSeatSlot struct {
	SeatKey     string  `json:"seatKey"`
	QueuePath   *string `json:"queuePath,omitempty"`
	DisplayName string  `json:"displayName"`
	TeamPrefix  *string `json:"teamPrefix,omitempty"`
	User        *User   `json:"user,omitempty"`
}

type User struct {
	ID           string        `json:"id"`
	Email        *string       `json:"email,omitempty"`
	DisplayName  *string       `json:"displayName,omitempty"`
	AvatarURL    *string       `json:"avatarUrl,omitempty"`
	AvatarKey    *string       `json:"avatarKey,omitempty"`
	AvatarSource *AvatarSource `json:"avatarSource,omitempty"`
	CreatedAt    time.Time     `json:"createdAt"`
	IsAdmin      bool          `json:"isAdmin"`
}

type AvatarSource string

const (
	AvatarSourceStarter      AvatarSource = "STARTER"
	AvatarSourceSpiritAnimal AvatarSource = "SPIRIT_ANIMAL"
	AvatarSourceNone         AvatarSource = "NONE"
)

var AllAvatarSource = []AvatarSource{
	AvatarSourceStarter,
	AvatarSourceSpiritAnimal,
	AvatarSourceNone,
}

func (e AvatarSource) IsValid() bool {
	switch e {
	case AvatarSourceStarter, AvatarSourceSpiritAnimal, AvatarSourceNone:
		return true
	}
	return false
}

func (e AvatarSource) String() string {
	return string(e)
}

func (e *AvatarSource) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AvatarSource(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AvatarSource", str)
	}
	return nil
}

func (e AvatarSource) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AvatarSource) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AvatarSource) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MatchResultStatus string

const (
	MatchResultStatusCompleted MatchResultStatus = "COMPLETED"
	MatchResultStatusCancelled MatchResultStatus = "CANCELLED"
	MatchResultStatusAbandoned MatchResultStatus = "ABANDONED"
)

var AllMatchResultStatus = []MatchResultStatus{
	MatchResultStatusCompleted,
	MatchResultStatusCancelled,
	MatchResultStatusAbandoned,
}

func (e MatchResultStatus) IsValid() bool {
	switch e {
	case MatchResultStatusCompleted, MatchResultStatusCancelled, MatchResultStatusAbandoned:
		return true
	}
	return false
}

func (e MatchResultStatus) String() string {
	return string(e)
}

func (e *MatchResultStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MatchResultStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MatchResultStatus", str)
	}
	return nil
}

func (e MatchResultStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MatchResultStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MatchResultStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PlayerFinishReason string

const (
	PlayerFinishReasonCompleted  PlayerFinishReason = "COMPLETED"
	PlayerFinishReasonEliminated PlayerFinishReason = "ELIMINATED"
	PlayerFinishReasonForfeit    PlayerFinishReason = "FORFEIT"
	PlayerFinishReasonDisconnect PlayerFinishReason = "DISCONNECT"
)

var AllPlayerFinishReason = []PlayerFinishReason{
	PlayerFinishReasonCompleted,
	PlayerFinishReasonEliminated,
	PlayerFinishReasonForfeit,
	PlayerFinishReasonDisconnect,
}

func (e PlayerFinishReason) IsValid() bool {
	switch e {
	case PlayerFinishReasonCompleted, PlayerFinishReasonEliminated, PlayerFinishReasonForfeit, PlayerFinishReasonDisconnect:
		return true
	}
	return false
}

func (e PlayerFinishReason) String() string {
	return string(e)
}

func (e *PlayerFinishReason) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PlayerFinishReason(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PlayerFinishReason", str)
	}
	return nil
}

func (e PlayerFinishReason) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PlayerFinishReason) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PlayerFinishReason) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type QueueStatus string

const (
	QueueStatusWaiting QueueStatus = "WAITING"
	QueueStatusMatched QueueStatus = "MATCHED"
	QueueStatusLeft    QueueStatus = "LEFT"
)

var AllQueueStatus = []QueueStatus{
	QueueStatusWaiting,
	QueueStatusMatched,
	QueueStatusLeft,
}

func (e QueueStatus) IsValid() bool {
	switch e {
	case QueueStatusWaiting, QueueStatusMatched, QueueStatusLeft:
		return true
	}
	return false
}

func (e QueueStatus) String() string {
	return string(e)
}

func (e *QueueStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = QueueStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid QueueStatus", str)
	}
	return nil
}

func (e QueueStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *QueueStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e QueueStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SessionStatus string

const (
	SessionStatusPending SessionStatus = "PENDING"
	SessionStatusActive  SessionStatus = "ACTIVE"
	SessionStatusEnded   SessionStatus = "ENDED"
)

var AllSessionStatus = []SessionStatus{
	SessionStatusPending,
	SessionStatusActive,
	SessionStatusEnded,
}

func (e SessionStatus) IsValid() bool {
	switch e {
	case SessionStatusPending, SessionStatusActive, SessionStatusEnded:
		return true
	}
	return false
}

func (e SessionStatus) String() string {
	return string(e)
}

func (e *SessionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SessionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SessionStatus", str)
	}
	return nil
}

func (e SessionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SessionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SessionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SpiritAnimalReadingStatus string

const (
	SpiritAnimalReadingStatusGeneratingQuestions SpiritAnimalReadingStatus = "GENERATING_QUESTIONS"
	SpiritAnimalReadingStatusAwaitingAnswers     SpiritAnimalReadingStatus = "AWAITING_ANSWERS"
	SpiritAnimalReadingStatusProcessing          SpiritAnimalReadingStatus = "PROCESSING"
	SpiritAnimalReadingStatusReady               SpiritAnimalReadingStatus = "READY"
	SpiritAnimalReadingStatusCompleted           SpiritAnimalReadingStatus = "COMPLETED"
	SpiritAnimalReadingStatusFailed              SpiritAnimalReadingStatus = "FAILED"
)

var AllSpiritAnimalReadingStatus = []SpiritAnimalReadingStatus{
	SpiritAnimalReadingStatusGeneratingQuestions,
	SpiritAnimalReadingStatusAwaitingAnswers,
	SpiritAnimalReadingStatusProcessing,
	SpiritAnimalReadingStatusReady,
	SpiritAnimalReadingStatusCompleted,
	SpiritAnimalReadingStatusFailed,
}

func (e SpiritAnimalReadingStatus) IsValid() bool {
	switch e {
	case SpiritAnimalReadingStatusGeneratingQuestions, SpiritAnimalReadingStatusAwaitingAnswers, SpiritAnimalReadingStatusProcessing, SpiritAnimalReadingStatusReady, SpiritAnimalReadingStatusCompleted, SpiritAnimalReadingStatusFailed:
		return true
	}
	return false
}

func (e SpiritAnimalReadingStatus) String() string {
	return string(e)
}

func (e *SpiritAnimalReadingStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SpiritAnimalReadingStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SpiritAnimalReadingStatus", str)
	}
	return nil
}

func (e SpiritAnimalReadingStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SpiritAnimalReadingStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SpiritAnimalReadingStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
