package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/scruffyprodigy/playhub/graph/model"
	"github.com/scruffyprodigy/playhub/internal/auth"
)

// CreateGuestSession is the resolver for the createGuestSession field.
func (r *mutationResolver) CreateGuestSession(ctx context.Context) (*model.User, error) {
	authService, err := r.requireAuth()
	if err != nil {
		return nil, err
	}
	if _, err := r.requireStore(); err != nil {
		return nil, err
	}

	user, sessionToken, err := authService.CreateGuestSession(ctx)
	if err != nil {
		return nil, err
	}
	return finishSignIn(ctx, authService, user, sessionToken)
}

// RequestLinkEmail is the resolver for the requestLinkEmail field.
func (r *mutationResolver) RequestLinkEmail(ctx context.Context, email string) (bool, error) {
	authService, err := r.requireAuth()
	if err != nil {
		return false, err
	}
	userID, err := requireAuthenticatedUserID(ctx)
	if err != nil {
		return false, err
	}

	if err := authService.RequestLinkEmail(ctx, userID, email); err != nil {
		return false, err
	}
	return true, nil
}

// CompleteLinkEmailWithCode is the resolver for the completeLinkEmailWithCode field.
func (r *mutationResolver) CompleteLinkEmailWithCode(ctx context.Context, email string, code string, confirmMerge *bool) (*model.User, error) {
	authService, err := r.requireAuth()
	if err != nil {
		return nil, err
	}
	if _, err := r.requireStore(); err != nil {
		return nil, err
	}

	confirmed := confirmMerge != nil && *confirmMerge
	user, sessionToken, err := authService.CompleteLinkEmailWithCode(ctx, email, code, confirmed)
	if err != nil {
		return nil, err
	}
	return finishSignIn(ctx, authService, user, sessionToken)
}

// CompleteLinkEmailWithLink is the resolver for the completeLinkEmailWithLink field.
func (r *mutationResolver) CompleteLinkEmailWithLink(ctx context.Context, token string, confirmMerge *bool) (*model.User, error) {
	authService, err := r.requireAuth()
	if err != nil {
		return nil, err
	}
	if _, err := r.requireStore(); err != nil {
		return nil, err
	}

	confirmed := confirmMerge != nil && *confirmMerge
	user, sessionToken, err := authService.CompleteLinkEmailWithToken(ctx, token, confirmed)
	if err != nil {
		return nil, err
	}
	return finishSignIn(ctx, authService, user, sessionToken)
}

// RemoveLinkedEmail is the resolver for the removeLinkedEmail field.
func (r *mutationResolver) RemoveLinkedEmail(ctx context.Context, emailID string) (*model.User, error) {
	authService, err := r.requireAuth()
	if err != nil {
		return nil, err
	}
	userID, err := requireAuthenticatedUserID(ctx)
	if err != nil {
		return nil, err
	}
	parsedEmailID, err := parseUUID(emailID, "email id")
	if err != nil {
		return nil, err
	}

	user, err := authService.RemoveLinkedEmail(ctx, userID, parsedEmailID)
	if err != nil {
		return nil, err
	}
	return ToGraphQLUser(user), nil
}

// SetPrimaryEmail is the resolver for the setPrimaryEmail field.
func (r *mutationResolver) SetPrimaryEmail(ctx context.Context, emailID string) (*model.User, error) {
	authService, err := r.requireAuth()
	if err != nil {
		return nil, err
	}
	userID, err := requireAuthenticatedUserID(ctx)
	if err != nil {
		return nil, err
	}
	parsedEmailID, err := parseUUID(emailID, "email id")
	if err != nil {
		return nil, err
	}

	user, err := authService.SetPrimaryEmail(ctx, userID, parsedEmailID)
	if err != nil {
		return nil, err
	}
	return ToGraphQLUser(user), nil
}

// RemoveLinkedIdentity is the resolver for the removeLinkedIdentity field.
func (r *mutationResolver) RemoveLinkedIdentity(ctx context.Context, identityID string) (*model.User, error) {
	authService, err := r.requireAuth()
	if err != nil {
		return nil, err
	}
	userID, err := requireAuthenticatedUserID(ctx)
	if err != nil {
		return nil, err
	}
	parsedID, err := parseUUID(identityID, "identity id")
	if err != nil {
		return nil, err
	}

	user, err := authService.RemoveLinkedIdentity(ctx, userID, parsedID)
	if err != nil {
		return nil, err
	}
	return ToGraphQLUser(user), nil
}

// MyAccount is the resolver for the myAccount field.
func (r *queryResolver) MyAccount(ctx context.Context) (*model.Account, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	authService, err := r.requireAuth()
	if err != nil {
		return nil, err
	}

	user, err := authService.GetAuthenticatedUser(ctx)
	if err != nil {
		return nil, err
	}
	if user == nil {
		return nil, nil
	}
	return buildAccount(ctx, st, user)
}

// PreviewLinkEmail is the resolver for the previewLinkEmail field.
func (r *queryResolver) PreviewLinkEmail(ctx context.Context, email string) (*model.EmailLinkPreview, error) {
	authService, err := r.requireAuth()
	if err != nil {
		return nil, err
	}
	userID, err := requireAuthenticatedUserID(ctx)
	if err != nil {
		return nil, err
	}

	preview, err := authService.PreviewLinkEmail(ctx, userID, email)
	if err != nil {
		return nil, err
	}
	return ToGraphQLEmailLinkPreview(preview), nil
}

// EnabledOAuthProviders is the resolver for the enabledOAuthProviders field.
func (r *queryResolver) EnabledOAuthProviders(ctx context.Context) ([]model.AuthProvider, error) {
	_ = ctx
	var providers []model.AuthProvider
	for _, name := range auth.EnabledOAuthProviders() {
		provider, err := toGraphQLAuthProvider(name)
		if err != nil {
			continue
		}
		providers = append(providers, provider)
	}
	return providers, nil
}

// Emails is the resolver for the emails field.
func (r *userResolver) Emails(ctx context.Context, obj *model.User) ([]*model.UserEmail, error) {
	if obj == nil {
		return []*model.UserEmail{}, nil
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	return loadUserEmails(ctx, st, obj.ID)
}

// Identities is the resolver for the identities field.
func (r *userResolver) Identities(ctx context.Context, obj *model.User) ([]*model.UserIdentity, error) {
	if obj == nil {
		return []*model.UserIdentity{}, nil
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	return loadUserIdentities(ctx, st, obj.ID)
}
