package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/scruffyprodigy/playhub/graph/model"
	"github.com/scruffyprodigy/playhub/internal/auth"
)

// RequestSignIn is the resolver for the requestSignIn field.
func (r *mutationResolver) RequestSignIn(ctx context.Context, email string) (bool, error) {
	authService, err := r.requireAuth()
	if err != nil {
		return false, err
	}
	if _, err := r.requireStore(); err != nil {
		return false, err
	}

	if err := authService.RequestMagicLink(ctx, email); err != nil {
		return false, err
	}
	return true, nil
}

// CompleteSignInWithLink is the resolver for the completeSignInWithLink field.
func (r *mutationResolver) CompleteSignInWithLink(ctx context.Context, token string) (*model.User, error) {
	authService, err := r.requireAuth()
	if err != nil {
		return nil, err
	}
	if _, err := r.requireStore(); err != nil {
		return nil, err
	}

	user, sessionToken, err := authService.CompleteMagicLogin(ctx, token)
	if err != nil {
		return nil, err
	}

	return finishSignIn(ctx, authService, user, sessionToken)
}

// CompleteSignInWithCode is the resolver for the completeSignInWithCode field.
func (r *mutationResolver) CompleteSignInWithCode(ctx context.Context, email string, code string) (*model.User, error) {
	authService, err := r.requireAuth()
	if err != nil {
		return nil, err
	}
	if _, err := r.requireStore(); err != nil {
		return nil, err
	}

	user, sessionToken, err := authService.CompleteLoginCode(ctx, email, code)
	if err != nil {
		return nil, err
	}

	return finishSignIn(ctx, authService, user, sessionToken)
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	authService, err := r.requireAuth()
	if err != nil {
		return false, err
	}

	authService.Logout(ctx)
	return true, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	authService, err := r.requireAuth()
	if err != nil {
		return nil, nil
	}
	if _, err := r.requireStore(); err != nil {
		return nil, err
	}

	user, err := authService.GetAuthenticatedUser(ctx)
	if err != nil {
		return nil, err
	}
	return ToGraphQLUser(user), nil
}

// SubscriptionAuth is the resolver for the subscriptionAuth field.
func (r *queryResolver) SubscriptionAuth(ctx context.Context) (*string, error) {
	token, ok := auth.SessionTokenFromContext(ctx)
	if !ok {
		return nil, nil
	}
	header := "Bearer " + token
	return &header, nil
}
