package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"errors"
	"fmt"

	"github.com/scruffyprodigy/playhub/graph/model"
	"github.com/scruffyprodigy/playhub/internal/auth"
	"github.com/scruffyprodigy/playhub/internal/avatars"
	"github.com/scruffyprodigy/playhub/internal/store"
)

// UpdatePlayerProfile is the resolver for the updatePlayerProfile field.
func (r *mutationResolver) UpdatePlayerProfile(ctx context.Context, displayName string, avatarKey *string) (*model.User, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	key := ""
	if avatarKey != nil {
		key = *avatarKey
	}
	user, err := st.UpdateUserProfile(ctx, userID, displayName, key, auth.LobbyPublicURL())
	if err != nil {
		switch {
		case errors.Is(err, store.ErrInvalidAvatarKey):
			return nil, fmt.Errorf("invalid avatar key")
		case errors.Is(err, store.ErrInvalidDisplayName):
			return nil, fmt.Errorf("invalid display name")
		default:
			return nil, err
		}
	}
	return ToGraphQLUser(user), nil
}

// StarterAvatars is the resolver for the starterAvatars field.
func (r *queryResolver) StarterAvatars(ctx context.Context) ([]*model.StarterAvatar, error) {
	origin := auth.LobbyPublicURL()
	out := make([]*model.StarterAvatar, len(avatars.StarterCatalog))
	for i, entry := range avatars.StarterCatalog {
		url := avatars.PublicAssetURL(origin, entry.File)
		out[i] = &model.StarterAvatar{
			Key:      entry.Key,
			Name:     entry.Name,
			Slot:     entry.Slot,
			ImageURL: url,
		}
	}
	return out, nil
}
