package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	"strings"

	"github.com/scruffyprodigy/playhub/graph/generated"
	"github.com/scruffyprodigy/playhub/graph/model"
	"github.com/scruffyprodigy/playhub/internal/auth"
	"github.com/scruffyprodigy/playhub/internal/gameurl"
	"github.com/scruffyprodigy/playhub/internal/store"
)

// Modes is the resolver for the modes field.
func (r *gameResolver) Modes(ctx context.Context, obj *model.Game) ([]*model.GameMode, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	gameID, err := parseUUID(obj.ID, "game id")
	if err != nil {
		return nil, err
	}
	modes, err := st.ListGameModesByGameID(ctx, gameID)
	if err != nil {
		return nil, err
	}
	return ToGraphQLGameModes(modes), nil
}

// Seats is the resolver for the seats field.
func (r *gameModeResolver) Seats(ctx context.Context, obj *model.GameMode) ([]*model.GameModeSeat, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	modeID, err := parseUUID(obj.ID, "mode id")
	if err != nil {
		return nil, err
	}
	seats, err := st.ListGameModeSeats(ctx, modeID)
	if err != nil {
		return nil, err
	}
	return ToGraphQLGameModeSeats(seats), nil
}

// QueuePaths is the resolver for the queuePaths field.
func (r *gameModeResolver) QueuePaths(ctx context.Context, obj *model.GameMode) ([]*model.GameModeQueuePath, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	modeID, err := parseUUID(obj.ID, "mode id")
	if err != nil {
		return nil, err
	}
	mode, err := st.GetGameModeByID(ctx, modeID)
	if err != nil {
		return nil, err
	}
	return ToGraphQLQueuePaths(mode.SeatTemplate)
}

// Queues is the resolver for the queues field.
func (r *gameModeResolver) Queues(ctx context.Context, obj *model.GameMode) ([]*model.ModeQueue, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	modeID, err := parseUUID(obj.ID, "mode id")
	if err != nil {
		return nil, err
	}
	queues, err := st.ListModeQueuesByModeID(ctx, modeID)
	if err != nil {
		return nil, err
	}
	return ToGraphQLModeQueues(queues), nil
}

// WaitingCount is the resolver for the waitingCount field.
func (r *modeQueueResolver) WaitingCount(ctx context.Context, obj *model.ModeQueue) (int, error) {
	st, err := r.requireStore()
	if err != nil {
		return 0, err
	}
	queueID, err := parseUUID(obj.ID, "queue id")
	if err != nil {
		return 0, err
	}
	return st.CountWaitingInModeQueue(ctx, queueID)
}

// RegisterGame is the resolver for the registerGame field.
func (r *mutationResolver) RegisterGame(ctx context.Context, input model.RegisterGameInput) (*model.RegisterGamePayload, error) {
	if _, err := r.requireAdmin(ctx); err != nil {
		return nil, err
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}

	manifest, err := r.manifestFetcher().Fetch(ctx, input.APIBaseURL, "")
	if err != nil {
		return nil, err
	}

	if err := gameurl.ValidateOutboundURL(ctx, input.APIBaseURL, auth.IsProductionEnv()); err != nil {
		return nil, fmt.Errorf("apiBaseUrl: %w", err)
	}
	if err := gameurl.ValidateOutboundURL(ctx, input.PlayURL, auth.IsProductionEnv()); err != nil {
		return nil, fmt.Errorf("playUrl: %w", err)
	}

	var description *string
	if input.Description != nil {
		trimmed := strings.TrimSpace(*input.Description)
		if trimmed != "" {
			description = &trimmed
		}
	}
	name := ""
	if input.Name != nil {
		name = strings.TrimSpace(*input.Name)
	}

	iconURL := strings.TrimSpace(input.IconURL)
	if iconURL == "" {
		return nil, fmt.Errorf("iconUrl is required")
	}
	heroURL := strings.TrimSpace(input.HeroURL)
	if heroURL == "" {
		return nil, fmt.Errorf("heroUrl is required")
	}

	result, err := st.RegisterGame(ctx, store.RegisterGameParams{
		Slug:        input.Slug,
		Name:        name,
		Description: description,
		IconURL:     iconURL,
		HeroURL:     heroURL,
		PlayURL:     input.PlayURL,
		APIBaseURL:  input.APIBaseURL,
	}, manifest)
	if err != nil {
		return nil, err
	}

	if err := r.publishKickedWaiters(ctx, result.Kicked); err != nil {
		return nil, err
	}

	serviceToken, err := auth.FormatGameServiceToken(result.Game.ID)
	if err != nil {
		return nil, err
	}

	return &model.RegisterGamePayload{
		Game:          ToGraphQLGame(result.Game),
		WebhookSecret: result.WebhookSecret,
		ServiceToken:  serviceToken,
	}, nil
}

// RefreshGameManifest is the resolver for the refreshGameManifest field.
func (r *mutationResolver) RefreshGameManifest(ctx context.Context, gameID string) (*model.Game, error) {
	if _, err := r.requireAdmin(ctx); err != nil {
		return nil, err
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}

	id, err := parseUUID(gameID, "game id")
	if err != nil {
		return nil, err
	}
	game, err := st.GetGameByID(ctx, id)
	if err != nil {
		return nil, err
	}

	result, err := r.syncGameManifest(ctx, game)
	if err != nil {
		return nil, err
	}

	if err := r.publishKickedWaiters(ctx, result.Kicked); err != nil {
		return nil, err
	}

	return ToGraphQLGame(result.Game), nil
}

// GameMode returns generated.GameModeResolver implementation.
func (r *Resolver) GameMode() generated.GameModeResolver { return &gameModeResolver{r} }

// ModeQueue returns generated.ModeQueueResolver implementation.
func (r *Resolver) ModeQueue() generated.ModeQueueResolver { return &modeQueueResolver{r} }

type gameModeResolver struct{ *Resolver }
type modeQueueResolver struct{ *Resolver }
