package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/google/uuid"
	"github.com/scruffyprodigy/playhub/graph/generated"
	"github.com/scruffyprodigy/playhub/graph/model"
	"github.com/scruffyprodigy/playhub/internal/pubsub"
	"github.com/scruffyprodigy/playhub/internal/store"
)

// JoinQueue is the resolver for the joinQueue field.
func (r *mutationResolver) JoinQueue(ctx context.Context, queueID string, queuePath *string) (*model.JoinResult, error) {
	modeQueueID, err := parseUUID(queueID, "queue id")
	if err != nil {
		return nil, err
	}
	path := ""
	if queuePath != nil {
		path = strings.TrimSpace(*queuePath)
	}
	return r.joinQueueInternal(ctx, modeQueueID, path)
}

// LeaveQueue is the resolver for the leaveQueue field.
func (r *mutationResolver) LeaveQueue(ctx context.Context, queueID string) (bool, error) {
	st, err := r.requireStore()
	if err != nil {
		return false, err
	}

	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return false, err
	}
	modeQueueID, err := parseUUID(queueID, "queue id")
	if err != nil {
		return false, err
	}

	view, err := st.GetUserModeQueueView(ctx, modeQueueID, userID)
	if err != nil {
		return false, err
	}

	queuedCount, err := st.LeaveModeQueue(ctx, modeQueueID, userID)
	if err != nil {
		return false, err
	}
	if err := r.publishQueueLeft(ctx, view.GameID, modeQueueID, userID, queuedCount, ""); err != nil {
		return false, err
	}
	return true, nil
}

// GrantGood is the resolver for the grantGood field.
func (r *mutationResolver) GrantGood(ctx context.Context, userID string, goodID string, quantity *int) (bool, error) {
	if _, err := r.requireAdmin(ctx); err != nil {
		return false, err
	}

	st, err := r.requireStore()
	if err != nil {
		return false, err
	}

	uid, err := parseUUID(userID, "user id")
	if err != nil {
		return false, err
	}
	gid, err := parseUUID(goodID, "good id")
	if err != nil {
		return false, err
	}

	qty := 1
	if quantity != nil {
		qty = *quantity
	}

	if err := st.EnsureUserExists(ctx, uid); err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return false, fmt.Errorf("user not found")
		}
		return false, err
	}
	if err := st.EnsureDigitalGoodExists(ctx, gid); err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return false, fmt.Errorf("good not found")
		}
		return false, err
	}
	if err := st.GrantInventoryItem(ctx, uid, gid, qty); err != nil {
		return false, err
	}
	return true, nil
}

// RevokeGood is the resolver for the revokeGood field.
func (r *mutationResolver) RevokeGood(ctx context.Context, userID string, goodID string, quantity *int) (bool, error) {
	if _, err := r.requireAdmin(ctx); err != nil {
		return false, err
	}

	st, err := r.requireStore()
	if err != nil {
		return false, err
	}

	uid, err := parseUUID(userID, "user id")
	if err != nil {
		return false, err
	}
	gid, err := parseUUID(goodID, "good id")
	if err != nil {
		return false, err
	}

	qty := 1
	if quantity != nil {
		qty = *quantity
	}

	if err := st.RevokeInventoryItem(ctx, uid, gid, qty); err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return false, fmt.Errorf("insufficient inventory")
		}
		return false, err
	}
	return true, nil
}

// Version is the resolver for the version field.
func (r *queryResolver) Version(ctx context.Context) (string, error) {
	return "1.0.0", nil
}

// Healthz is the resolver for the healthz field.
func (r *queryResolver) Healthz(ctx context.Context) (string, error) {
	return "ok", nil
}

// Games is the resolver for the games field.
func (r *queryResolver) Games(ctx context.Context, limit *int, offset *int) ([]*model.Game, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}

	pageSize := 20
	if limit != nil {
		pageSize = *limit
	}
	pageOffset := 0
	if offset != nil {
		pageOffset = *offset
	}

	games, err := st.ListCatalogGames(ctx, pageSize, pageOffset)
	if err != nil {
		return nil, err
	}

	return ToGraphQLGames(games), nil
}

// Game is the resolver for the game field.
func (r *queryResolver) Game(ctx context.Context, id string) (*model.Game, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}

	gameID, err := parseUUID(id, "game id")
	if err != nil {
		return nil, err
	}

	game, err := st.GetGameByID(ctx, gameID)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return nil, fmt.Errorf("game not found")
		}
		return nil, err
	}

	return ToGraphQLGame(game), nil
}

// Session is the resolver for the session field.
func (r *queryResolver) Session(ctx context.Context, id string) (*model.Session, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}

	sessionID, err := parseUUID(id, "session id")
	if err != nil {
		return nil, err
	}

	session, err := st.GetSessionByID(ctx, sessionID)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return nil, fmt.Errorf("session not found")
		}
		return nil, err
	}

	return ToGraphQLSession(session, nil), nil
}

// Goods is the resolver for the goods field.
func (r *queryResolver) Goods(ctx context.Context, gameID *string) ([]*model.DigitalGood, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}

	var filterGameID *uuid.UUID
	if gameID != nil {
		id, err := parseUUID(*gameID, "game id")
		if err != nil {
			return nil, err
		}
		filterGameID = &id
	}

	goods, err := st.ListDigitalGoods(ctx, filterGameID)
	if err != nil {
		return nil, err
	}
	return ToGraphQLDigitalGoods(goods), nil
}

// MyInventory is the resolver for the myInventory field.
func (r *queryResolver) MyInventory(ctx context.Context, gameID *string) ([]*model.Entitlement, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}

	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}

	var filterGameID *uuid.UUID
	if gameID != nil {
		id, err := parseUUID(*gameID, "game id")
		if err != nil {
			return nil, err
		}
		filterGameID = &id
	}

	items, err := st.ListUserInventory(ctx, userID, filterGameID)
	if err != nil {
		return nil, err
	}
	return ToGraphQLEntitlements(items), nil
}

// MyQueueStatus is the resolver for the myQueueStatus field.
func (r *queryResolver) MyQueueStatus(ctx context.Context, queueID string) (*model.JoinResult, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}

	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	modeQueueID, err := parseUUID(queueID, "queue id")
	if err != nil {
		return nil, err
	}

	view, err := st.GetUserModeQueueView(ctx, modeQueueID, userID)
	if err != nil {
		return nil, err
	}

	launchURL := ""
	if view.Matched && view.SessionID != nil {
		game, gErr := st.GetGameByID(ctx, view.GameID)
		if gErr != nil {
			return nil, gErr
		}
		launchURL, err = r.signLaunchURL(ctx, game, *view.SessionID, userID)
		if err != nil {
			return nil, fmt.Errorf("launch url: %w", err)
		}
	}
	return joinResultFromQueueView(view, launchURL), nil
}

// MyActiveQueue is the resolver for the myActiveQueue field.
func (r *queryResolver) MyActiveQueue(ctx context.Context) (*model.ActiveQueue, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}

	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}

	active, err := st.GetUserActiveQueue(ctx, userID)
	if err != nil {
		return nil, err
	}
	if active == nil {
		return nil, nil
	}

	queueID := active.ModeQueueID.String()
	gameID := active.GameID.String()
	resp := &model.ActiveQueue{
		QueueID:  queueID,
		GameID:   gameID,
		GameName: active.GameName,
	}
	if active.Waiting {
		resp.Status = model.QueueStatusWaiting
		count := active.QueuedCount
		resp.QueuedCount = &count
		resp.QueuePath = joinResultQueuePath(active.QueuePath)
		if modeQueue, mqErr := st.GetModeQueueByID(ctx, active.ModeQueueID); mqErr == nil {
			if mode, mErr := st.GetGameModeByID(ctx, modeQueue.ModeID); mErr == nil {
				resp.QueuePathDisplayName = queuePathDisplayName(mode.SeatTemplate, active.QueuePath)
			}
		}
		return resp, nil
	}

	resp.Status = model.QueueStatusMatched
	if active.SessionID != nil {
		game, gErr := st.GetGameByID(ctx, active.GameID)
		if gErr != nil {
			return nil, gErr
		}
		launchURL, uErr := r.signLaunchURL(ctx, game, *active.SessionID, userID)
		if uErr != nil {
			return nil, fmt.Errorf("launch url: %w", uErr)
		}
		if launchURL != "" {
			resp.JoinURL = &launchURL
		}
	}
	return resp, nil
}

// Player is the resolver for the player field.
func (r *queryResolver) Player(ctx context.Context, id string) (*model.PublicPlayer, error) {
	if err := requireGameServiceAuth(ctx); err != nil {
		return nil, err
	}

	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}

	playerID, err := parseUUID(id, "player id")
	if err != nil {
		return nil, err
	}

	user, err := st.GetUserByID(ctx, playerID)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return ToGraphQLPublicPlayer(user), nil
}

// QueueUpdated is the resolver for the queueUpdated field.
func (r *subscriptionResolver) QueueUpdated(ctx context.Context, queueID string) (<-chan *model.QueueUpdate, error) {
	if r.PubSub == nil {
		return nil, fmt.Errorf("pubsub is not configured")
	}

	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}

	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}

	modeQueueID, err := parseUUID(queueID, "queue id")
	if err != nil {
		return nil, err
	}

	modeQueue, err := st.GetModeQueueByID(ctx, modeQueueID)
	if err != nil {
		return nil, err
	}
	gameMode, err := st.GetGameModeByID(ctx, modeQueue.ModeID)
	if err != nil {
		return nil, err
	}
	game, err := st.GetGameByID(ctx, gameMode.GameID)
	if err != nil {
		return nil, err
	}

	view, err := st.GetUserModeQueueView(ctx, modeQueueID, userID)
	if err != nil {
		return nil, err
	}

	initialLaunchURL := ""
	if view.Matched && view.SessionID != nil {
		initialLaunchURL, err = r.signLaunchURL(ctx, game, *view.SessionID, userID)
		if err != nil {
			return nil, fmt.Errorf("launch url: %w", err)
		}
	}
	initial := queueUpdateFromView(view, initialLaunchURL)

	messages, unsubscribe, err := r.PubSub.Subscribe(ctx, pubsub.UserQueueChannel(userID.String()))
	if err != nil {
		return nil, err
	}

	updates := make(chan *model.QueueUpdate, 2)
	go func() {
		defer close(updates)
		defer unsubscribe()

		if initial != nil {
			select {
			case updates <- initial:
			case <-ctx.Done():
				return
			}
		}

		for {
			select {
			case <-ctx.Done():
				return
			case payload, ok := <-messages:
				if !ok {
					return
				}
				event, err := pubsub.UnmarshalQueueEvent(payload)
				if err != nil || event.QueueID != modeQueueID.String() {
					continue
				}
				update := toGraphQLQueueUpdate(event)
				select {
				case updates <- update:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return updates, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
