package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/scruffyprodigy/playhub/graph/generated"
	"github.com/scruffyprodigy/playhub/graph/model"
	"github.com/scruffyprodigy/playhub/internal/auth"
	"github.com/scruffyprodigy/playhub/internal/pubsub"
	"github.com/scruffyprodigy/playhub/internal/store"
)

// LoginMagic is the resolver for the loginMagic field.
func (r *mutationResolver) LoginMagic(ctx context.Context, email string) (bool, error) {
	authService, err := r.requireAuth()
	if err != nil {
		return false, err
	}
	if _, err := r.requireStore(); err != nil {
		return false, err
	}

	if err := authService.RequestMagicLink(ctx, email); err != nil {
		return false, err
	}
	return true, nil
}

// CompleteMagic is the resolver for the completeMagic field.
func (r *mutationResolver) CompleteMagic(ctx context.Context, token string) (*model.User, error) {
	authService, err := r.requireAuth()
	if err != nil {
		return nil, err
	}
	if _, err := r.requireStore(); err != nil {
		return nil, err
	}

	user, sessionToken, err := authService.CompleteMagicLogin(ctx, token)
	if err != nil {
		return nil, err
	}

	if writer, ok := auth.ResponseWriterFromContext(ctx); ok {
		auth.SetSessionCookie(writer, sessionToken, authService.CookieConfig())
	}

	return ToGraphQLUser(user), nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	authService, err := r.requireAuth()
	if err != nil {
		return false, err
	}

	authService.Logout(ctx)
	return true, nil
}

// CreateGame is the resolver for the createGame field.
func (r *mutationResolver) CreateGame(ctx context.Context, input model.CreateGameInput) (*model.Game, error) {
	// TODO: Implement proper database insertion and validation
	// For now, return a mock game
	return &model.Game{
		ID:        uuid.New().String(),
		Name:      input.Name,
		CreatedAt: time.Now(),
	}, nil
}

// JoinGame is the resolver for the joinGame field.
func (r *mutationResolver) JoinGame(ctx context.Context, gameID string) (*model.JoinResult, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}

	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	gameUUID, err := parseUUID(gameID, "game id")
	if err != nil {
		return nil, err
	}

	result, err := st.JoinGameQueue(ctx, gameUUID, userID)
	if err != nil {
		if errors.Is(err, store.ErrAlreadyMatched) {
			return nil, fmt.Errorf("you are already in a match for this game")
		}
		return nil, err
	}

	var launchURLs map[uuid.UUID]string
	if result.Status == store.QueueStatusMatched && result.SessionID != nil {
		game, gErr := st.GetGameByID(ctx, gameUUID)
		if gErr != nil {
			return nil, gErr
		}
		launchURLs, err = r.finalizeMatchedSession(ctx, game, *result.SessionID, result.NotifyUserIDs)
		if err != nil {
			return nil, err
		}
	}

	if err := r.publishQueueResult(ctx, gameUUID, result, launchURLs); err != nil {
		return nil, err
	}

	return joinResultAfterJoin(result, userID, launchURLs), nil
}

// LeaveQueue is the resolver for the leaveQueue field.
func (r *mutationResolver) LeaveQueue(ctx context.Context, gameID string) (bool, error) {
	st, err := r.requireStore()
	if err != nil {
		return false, err
	}

	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return false, err
	}
	gameUUID, err := parseUUID(gameID, "game id")
	if err != nil {
		return false, err
	}

	queuedCount, err := st.LeaveGameQueue(ctx, gameUUID, userID)
	if err != nil {
		return false, err
	}
	if err := r.publishQueueLeft(ctx, gameUUID, userID, queuedCount); err != nil {
		return false, err
	}
	return true, nil
}

// GrantGood is the resolver for the grantGood field.
func (r *mutationResolver) GrantGood(ctx context.Context, userID string, goodID string, quantity *int) (bool, error) {
	// TODO: Implement proper entitlement granting logic
	// For now, return true to simulate successful grant

	// TODO: Validate userID and goodID exist
	// TODO: Create entitlement record in database
	// TODO: Use quantity parameter for entitlement amount

	return true, nil
}

// RevokeGood is the resolver for the revokeGood field.
func (r *mutationResolver) RevokeGood(ctx context.Context, userID string, goodID string, quantity *int) (bool, error) {
	// TODO: Implement proper entitlement revocation logic
	// For now, return true to simulate successful revocation

	// TODO: Validate userID and goodID exist
	// TODO: Update or remove entitlement record in database
	// TODO: Use quantity parameter for revocation amount

	return true, nil
}

// Version is the resolver for the version field.
func (r *queryResolver) Version(ctx context.Context) (string, error) {
	return "1.0.0", nil
}

// Healthz is the resolver for the healthz field.
func (r *queryResolver) Healthz(ctx context.Context) (string, error) {
	return "ok", nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	authService, err := r.requireAuth()
	if err != nil {
		return nil, nil
	}
	if _, err := r.requireStore(); err != nil {
		return nil, err
	}

	user, err := authService.GetAuthenticatedUser(ctx)
	if err != nil {
		return nil, err
	}
	return ToGraphQLUser(user), nil
}

// Games is the resolver for the games field.
func (r *queryResolver) Games(ctx context.Context, limit *int, offset *int) ([]*model.Game, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}

	pageSize := 20
	if limit != nil {
		pageSize = *limit
	}
	pageOffset := 0
	if offset != nil {
		pageOffset = *offset
	}

	games, err := st.ListDemoGames(ctx, pageSize, pageOffset)
	if err != nil {
		return nil, err
	}

	return ToGraphQLGames(games), nil
}

// Game is the resolver for the game field.
func (r *queryResolver) Game(ctx context.Context, id string) (*model.Game, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}

	gameID, err := parseUUID(id, "game id")
	if err != nil {
		return nil, err
	}

	game, err := st.GetGameByID(ctx, gameID)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return nil, fmt.Errorf("game not found")
		}
		return nil, err
	}

	return ToGraphQLGame(game), nil
}

// Session is the resolver for the session field.
func (r *queryResolver) Session(ctx context.Context, id string) (*model.Session, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}

	sessionID, err := parseUUID(id, "session id")
	if err != nil {
		return nil, err
	}

	session, err := st.GetSessionByID(ctx, sessionID)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return nil, fmt.Errorf("session not found")
		}
		return nil, err
	}

	return ToGraphQLSession(session, nil), nil
}

// Goods is the resolver for the goods field.
func (r *queryResolver) Goods(ctx context.Context, gameID *string) ([]*model.DigitalGood, error) {
	// TODO: Implement proper database query
	// For now, return mock goods
	goods := []*model.DigitalGood{
		{
			ID:          uuid.New().String(),
			Code:        "SKIN_001",
			Name:        "Cool Skin",
			Description: &[]string{"A really cool skin for your character"}[0],
		},
		{
			ID:          uuid.New().String(),
			Code:        "WEAPON_001",
			Name:        "Epic Weapon",
			Description: &[]string{"An epic weapon with special abilities"}[0],
		},
	}

	// If gameID is specified, filter goods for that game
	if gameID != nil {
		// TODO: Implement proper filtering
		// For now, return all goods
	}

	return goods, nil
}

// MyInventory is the resolver for the myInventory field.
func (r *queryResolver) MyInventory(ctx context.Context, gameID *string) ([]*model.Entitlement, error) {
	// TODO: Implement proper database query and authentication
	// For now, return mock inventory
	entitlements := []*model.Entitlement{
		{
			Good: &model.DigitalGood{
				ID:          uuid.New().String(),
				Code:        "SKIN_001",
				Name:        "Cool Skin",
				Description: &[]string{"A really cool skin for your character"}[0],
			},
			Quantity:  1,
			GrantedAt: time.Now().Add(-1 * time.Hour),
		},
	}

	// If gameID is specified, filter entitlements for that game
	if gameID != nil {
		// TODO: Implement proper filtering
		// For now, return all entitlements
	}

	return entitlements, nil
}

// MyQueueStatus is the resolver for the myQueueStatus field.
func (r *queryResolver) MyQueueStatus(ctx context.Context, gameID string) (*model.JoinResult, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}

	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	gameUUID, err := parseUUID(gameID, "game id")
	if err != nil {
		return nil, err
	}

	view, err := st.GetUserQueueView(ctx, gameUUID, userID)
	if err != nil {
		return nil, err
	}

	launchURL := ""
	if view.Matched && view.SessionID != nil {
		game, gErr := st.GetGameByID(ctx, gameUUID)
		if gErr != nil {
			return nil, gErr
		}
		launchURL, err = r.signLaunchURL(ctx, game, *view.SessionID, userID)
		if err != nil {
			return nil, fmt.Errorf("launch url: %w", err)
		}
	}
	return joinResultFromQueueView(view, launchURL), nil
}

// SubscriptionAuth is the resolver for the subscriptionAuth field.
func (r *queryResolver) SubscriptionAuth(ctx context.Context) (*string, error) {
	token, ok := auth.SessionTokenFromContext(ctx)
	if !ok {
		return nil, nil
	}
	header := "Bearer " + token
	return &header, nil
}

// QueueUpdated is the resolver for the queueUpdated field.
func (r *subscriptionResolver) QueueUpdated(ctx context.Context, gameID string) (<-chan *model.QueueUpdate, error) {
	if r.PubSub == nil {
		return nil, fmt.Errorf("pubsub is not configured")
	}

	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}

	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}

	gameUUID, err := parseUUID(gameID, "game id")
	if err != nil {
		return nil, err
	}

	game, err := st.GetGameByID(ctx, gameUUID)
	if err != nil {
		return nil, err
	}

	view, err := st.GetUserQueueView(ctx, gameUUID, userID)
	if err != nil {
		return nil, err
	}

	initialLaunchURL := ""
	if view.Matched && view.SessionID != nil {
		initialLaunchURL, err = r.signLaunchURL(ctx, game, *view.SessionID, userID)
		if err != nil {
			return nil, fmt.Errorf("launch url: %w", err)
		}
	}
	initial := queueUpdateFromView(view, gameUUID, initialLaunchURL)

	messages, unsubscribe, err := r.PubSub.Subscribe(ctx, pubsub.UserQueueChannel(userID.String()))
	if err != nil {
		return nil, err
	}

	updates := make(chan *model.QueueUpdate, 2)
	go func() {
		defer close(updates)
		defer unsubscribe()

		if initial != nil {
			select {
			case updates <- initial:
			case <-ctx.Done():
				return
			}
		}

		for {
			select {
			case <-ctx.Done():
				return
			case payload, ok := <-messages:
				if !ok {
					return
				}
				event, err := pubsub.UnmarshalQueueEvent(payload)
				if err != nil || event.GameID != gameUUID.String() {
					continue
				}
				update := toGraphQLQueueUpdate(event)
				select {
				case updates <- update:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return updates, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
