package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/scruffyprodigy/playhub/graph/model"
	"github.com/scruffyprodigy/playhub/internal/auth"
	"github.com/scruffyprodigy/playhub/internal/developer"
	"github.com/scruffyprodigy/playhub/internal/gameclient"
	"github.com/scruffyprodigy/playhub/internal/gameurl"
	"github.com/scruffyprodigy/playhub/internal/store"
)

// IntegrationChecks is the resolver for the integrationChecks field.
func (r *gameResolver) IntegrationChecks(ctx context.Context, obj *model.Game) ([]*model.GameIntegrationCheck, error) {
	if obj == nil {
		return []*model.GameIntegrationCheck{}, nil
	}
	gameID, err := parseUUID(obj.ID, "game id")
	if err != nil {
		return nil, err
	}
	userID, authErr := requireAuthUserID(ctx)
	if authErr != nil {
		return []*model.GameIntegrationCheck{}, nil
	}
	if obj.OwnerUserID == nil || *obj.OwnerUserID != userID.String() {
		return []*model.GameIntegrationCheck{}, nil
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	checks, err := st.ListIntegrationChecks(ctx, gameID)
	if err != nil {
		return nil, err
	}
	return ToGraphQLIntegrationChecks(checks), nil
}

// RegisterMyGame is the resolver for the registerMyGame field.
func (r *mutationResolver) RegisterMyGame(ctx context.Context, input model.RegisterMyGameInput) (*model.RegisterMyGamePayload, error) {
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}

	apiBaseURL := strings.TrimRight(strings.TrimSpace(input.APIBaseURL), "/")
	if err := gameurl.ValidateOutboundURL(ctx, apiBaseURL, auth.IsProductionEnv()); err != nil {
		return nil, fmt.Errorf("apiBaseUrl: %w", err)
	}

	var websiteURL, communityURL *string
	if input.WebsiteURL != nil {
		trimmed := strings.TrimSpace(*input.WebsiteURL)
		if trimmed != "" {
			websiteURL = &trimmed
		}
	}
	if input.CommunityURL != nil {
		trimmed := strings.TrimSpace(*input.CommunityURL)
		if trimmed != "" {
			communityURL = &trimmed
		}
	}

	var manifest *gameclient.Manifest
	var connectErr error
	manifest, connectErr = r.manifestFetcher().Fetch(ctx, apiBaseURL, "")

	result, err := st.RegisterMyGame(ctx, store.RegisterMyGameParams{
		OwnerUserID:      userID,
		Slug:             input.Slug,
		Name:             input.Name,
		ShortDescription: input.ShortDescription,
		APIBaseURL:       apiBaseURL,
		ContactEmail:     input.ContactEmail,
		WebsiteURL:       websiteURL,
		CommunityURL:     communityURL,
	}, manifest, connectErr)
	if err != nil {
		return nil, err
	}

	if result.Connected {
		if _, err := r.persistGameChecks(ctx, result.Game); err != nil {
			return nil, err
		}
	}

	serviceToken, err := auth.FormatGameServiceToken(result.Game.ID)
	if err != nil {
		return nil, err
	}

	payload := &model.RegisterMyGamePayload{
		Game:          ToGraphQLGame(result.Game),
		WebhookSecret: result.WebhookSecret,
		ServiceToken:  serviceToken,
		Connected:     result.Connected,
	}
	if result.ConnectError != "" {
		payload.ConnectError = &result.ConnectError
	}
	return payload, nil
}

// RunMyGameChecks is the resolver for the runMyGameChecks field.
func (r *mutationResolver) RunMyGameChecks(ctx context.Context, gameID string) ([]*model.GameIntegrationCheck, error) {
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	id, err := parseUUID(gameID, "game id")
	if err != nil {
		return nil, err
	}
	game, err := st.GetOwnedGame(ctx, id, userID)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return nil, fmt.Errorf("game not found")
		}
		return nil, err
	}
	return r.persistGameChecks(ctx, game)
}

// MyGames is the resolver for the myGames field.
func (r *queryResolver) MyGames(ctx context.Context) ([]*model.Game, error) {
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	games, err := st.ListMyGames(ctx, userID)
	if err != nil {
		return nil, err
	}
	return ToGraphQLGames(games), nil
}

// MyGame is the resolver for the myGame field.
func (r *queryResolver) MyGame(ctx context.Context, id string) (*model.Game, error) {
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	gameID, err := parseUUID(id, "game id")
	if err != nil {
		return nil, err
	}
	game, err := st.GetOwnedGame(ctx, gameID, userID)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return ToGraphQLGame(game), nil
}

// MyGameCredentials is the resolver for the myGameCredentials field.
func (r *queryResolver) MyGameCredentials(ctx context.Context, id string) (*model.MyGameCredentials, error) {
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	gameID, err := parseUUID(id, "game id")
	if err != nil {
		return nil, err
	}
	game, err := st.GetOwnedGame(ctx, gameID, userID)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}
	serviceToken, err := auth.FormatGameServiceToken(game.ID)
	if err != nil {
		return nil, err
	}
	secret := ""
	if game.WebhookSecret != nil {
		secret = *game.WebhookSecret
	}
	return &model.MyGameCredentials{
		ServiceToken:  serviceToken,
		WebhookSecret: secret,
	}, nil
}

// DeveloperIntegrationGuide is the resolver for the developerIntegrationGuide field.
func (r *queryResolver) DeveloperIntegrationGuide(ctx context.Context) (string, error) {
	return developer.IntegrationGuide(), nil
}
