package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/scruffyprodigy/playhub/graph/model"
	"github.com/scruffyprodigy/playhub/internal/auth"
	"github.com/scruffyprodigy/playhub/internal/developer"
	"github.com/scruffyprodigy/playhub/internal/gameclient"
	"github.com/scruffyprodigy/playhub/internal/gameurl"
	"github.com/scruffyprodigy/playhub/internal/store"
)

// IntegrationChecks is the resolver for the integrationChecks field.
func (r *gameResolver) IntegrationChecks(ctx context.Context, obj *model.Game) ([]*model.GameIntegrationCheck, error) {
	if obj == nil {
		return []*model.GameIntegrationCheck{}, nil
	}
	gameID, err := parseUUID(obj.ID, "game id")
	if err != nil {
		return nil, err
	}
	userID, authErr := requireAuthUserID(ctx)
	if authErr != nil {
		return []*model.GameIntegrationCheck{}, nil
	}
	if obj.OwnerUserID == nil || *obj.OwnerUserID != userID.String() {
		return []*model.GameIntegrationCheck{}, nil
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	checks, err := st.ListIntegrationChecks(ctx, gameID)
	if err != nil {
		return nil, err
	}
	return ToGraphQLIntegrationChecks(checks), nil
}

// CreateDeveloperAPIKey is the resolver for the createDeveloperApiKey field.
func (r *mutationResolver) CreateDeveloperAPIKey(ctx context.Context, name *string) (*model.CreateDeveloperAPIKeyPayload, error) {
	authService, err := r.requireAuth()
	if err != nil {
		return nil, err
	}
	user, err := authService.RequireNonGuestUser(ctx)
	if err != nil {
		return nil, err
	}
	userID := user.ID
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}

	keyName := "Integration agent"
	if name != nil && strings.TrimSpace(*name) != "" {
		keyName = strings.TrimSpace(*name)
	}

	rawKey, key, err := st.CreateDeveloperAPIKey(ctx, userID, keyName)
	if err != nil {
		return nil, err
	}

	return &model.CreateDeveloperAPIKeyPayload{
		APIKey: ToGraphQLDeveloperAPIKey(&key),
		Secret: rawKey,
	}, nil
}

// RevokeDeveloperAPIKey is the resolver for the revokeDeveloperApiKey field.
func (r *mutationResolver) RevokeDeveloperAPIKey(ctx context.Context, id string) (bool, error) {
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return false, err
	}
	st, err := r.requireStore()
	if err != nil {
		return false, err
	}
	keyID, err := parseUUID(id, "api key id")
	if err != nil {
		return false, err
	}
	if err := st.RevokeDeveloperAPIKey(ctx, keyID, userID); err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return false, fmt.Errorf("api key not found")
		}
		return false, err
	}
	return true, nil
}

// RegisterMyGame is the resolver for the registerMyGame field.
func (r *mutationResolver) RegisterMyGame(ctx context.Context, input model.RegisterMyGameInput) (*model.RegisterMyGamePayload, error) {
	authService, err := r.requireAuth()
	if err != nil {
		return nil, err
	}
	user, err := authService.RequireNonGuestUser(ctx)
	if err != nil {
		return nil, err
	}
	userID := user.ID
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}

	apiBaseURL := strings.TrimRight(strings.TrimSpace(input.APIBaseURL), "/")
	if err := gameurl.ValidateOutboundURL(ctx, apiBaseURL, auth.IsProductionEnv()); err != nil {
		return nil, fmt.Errorf("apiBaseUrl: %w", err)
	}

	var websiteURL, communityURL *string
	if input.WebsiteURL != nil {
		trimmed := strings.TrimSpace(*input.WebsiteURL)
		if trimmed != "" {
			websiteURL = &trimmed
		}
	}
	if input.CommunityURL != nil {
		trimmed := strings.TrimSpace(*input.CommunityURL)
		if trimmed != "" {
			communityURL = &trimmed
		}
	}

	var manifest *gameclient.Manifest
	var connectErr error
	manifest, connectErr = r.manifestFetcher().Fetch(ctx, apiBaseURL, "")

	result, err := st.RegisterMyGame(ctx, store.RegisterMyGameParams{
		OwnerUserID:      userID,
		Slug:             input.Slug,
		Name:             input.Name,
		ShortDescription: input.ShortDescription,
		APIBaseURL:       apiBaseURL,
		ContactEmail:     input.ContactEmail,
		WebsiteURL:       websiteURL,
		CommunityURL:     communityURL,
	}, manifest, connectErr)
	if err != nil {
		return nil, err
	}

	if result.Connected {
		if _, err := r.persistGameChecks(ctx, result.Game); err != nil {
			return nil, err
		}
	}

	serviceToken, err := auth.FormatGameServiceToken(result.Game.ID)
	if err != nil {
		return nil, err
	}

	payload := &model.RegisterMyGamePayload{
		Game:          ToGraphQLGame(result.Game),
		WebhookSecret: result.WebhookSecret,
		ServiceToken:  serviceToken,
		Connected:     result.Connected,
	}
	if result.ConnectError != "" {
		payload.ConnectError = &result.ConnectError
	}
	return payload, nil
}

// SyncMyGameManifest is the resolver for the syncMyGameManifest field.
func (r *mutationResolver) SyncMyGameManifest(ctx context.Context, gameID string) (*model.SyncMyGameManifestPayload, error) {
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	id, err := parseUUID(gameID, "game id")
	if err != nil {
		return nil, err
	}
	game, err := st.GetOwnedGame(ctx, id, userID)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return nil, fmt.Errorf("game not found")
		}
		return nil, err
	}
	if game.APIBaseURL == nil || strings.TrimSpace(*game.APIBaseURL) == "" {
		return nil, fmt.Errorf("game has no apiBaseUrl configured")
	}

	manifest, fetchErr := r.manifestFetcher().Fetch(ctx, *game.APIBaseURL, "")
	result, err := st.ConnectOwnedGame(ctx, id, userID, nil, manifest, fetchErr)
	if err != nil {
		return nil, err
	}
	if err := r.publishKickedWaiters(ctx, result.Kicked); err != nil {
		return nil, err
	}

	payload := &model.SyncMyGameManifestPayload{
		Game:    ToGraphQLGame(result.Game),
		Changed: result.Changed,
	}
	if result.ConnectError != "" {
		payload.ConnectError = &result.ConnectError
	}
	return payload, nil
}

// ConnectMyGame is the resolver for the connectMyGame field.
func (r *mutationResolver) ConnectMyGame(ctx context.Context, input model.ConnectMyGameInput) (*model.ConnectMyGamePayload, error) {
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	id, err := parseUUID(input.GameID, "game id")
	if err != nil {
		return nil, err
	}
	game, err := st.GetOwnedGame(ctx, id, userID)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return nil, fmt.Errorf("game not found")
		}
		return nil, err
	}

	apiBaseURL := ""
	var newURL *string
	if input.APIBaseURL != nil {
		trimmed := strings.TrimRight(strings.TrimSpace(*input.APIBaseURL), "/")
		if trimmed == "" {
			return nil, fmt.Errorf("apiBaseUrl: must not be empty")
		}
		if err := gameurl.ValidateOutboundURL(ctx, trimmed, auth.IsProductionEnv()); err != nil {
			return nil, fmt.Errorf("apiBaseUrl: %w", err)
		}
		newURL = &trimmed
		apiBaseURL = trimmed
	} else if game.APIBaseURL != nil {
		apiBaseURL = strings.TrimSpace(*game.APIBaseURL)
	}
	if apiBaseURL == "" {
		return nil, fmt.Errorf("apiBaseUrl is required")
	}

	manifest, fetchErr := r.manifestFetcher().Fetch(ctx, apiBaseURL, "")
	result, err := st.ConnectOwnedGame(ctx, id, userID, newURL, manifest, fetchErr)
	if err != nil {
		return nil, err
	}
	if err := r.publishKickedWaiters(ctx, result.Kicked); err != nil {
		return nil, err
	}

	if result.Connected {
		if _, err := r.persistGameChecks(ctx, result.Game); err != nil {
			return nil, err
		}
	}

	payload := &model.ConnectMyGamePayload{
		Game:      ToGraphQLGame(result.Game),
		Connected: result.Connected,
		Changed:   result.Changed,
	}
	if result.ConnectError != "" {
		payload.ConnectError = &result.ConnectError
	}
	return payload, nil
}

// RotateMyGameWebhookSecret is the resolver for the rotateMyGameWebhookSecret field.
func (r *mutationResolver) RotateMyGameWebhookSecret(ctx context.Context, gameID string) (*model.MyGameCredentials, error) {
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	id, err := parseUUID(gameID, "game id")
	if err != nil {
		return nil, err
	}
	secret, game, err := st.RotateMyGameWebhookSecret(ctx, id, userID)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return nil, fmt.Errorf("game not found")
		}
		return nil, err
	}
	serviceToken, err := auth.FormatGameServiceToken(game.ID)
	if err != nil {
		return nil, err
	}
	return &model.MyGameCredentials{
		ServiceToken:  serviceToken,
		WebhookSecret: secret,
	}, nil
}

// RunMyGameChecks is the resolver for the runMyGameChecks field.
func (r *mutationResolver) RunMyGameChecks(ctx context.Context, gameID string) ([]*model.GameIntegrationCheck, error) {
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	id, err := parseUUID(gameID, "game id")
	if err != nil {
		return nil, err
	}
	game, err := st.GetOwnedGame(ctx, id, userID)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return nil, fmt.Errorf("game not found")
		}
		return nil, err
	}
	return r.persistGameChecks(ctx, game)
}

// UpdateMyGameMetadata is the resolver for the updateMyGameMetadata field.
func (r *mutationResolver) UpdateMyGameMetadata(ctx context.Context, input model.UpdateMyGameMetadataInput) (*model.Game, error) {
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	gameID, err := parseUUID(input.GameID, "game id")
	if err != nil {
		return nil, err
	}
	if _, err := st.GetOwnedGame(ctx, gameID, userID); err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return nil, fmt.Errorf("game not found")
		}
		return nil, err
	}

	params := store.UpdateMyGameMetadataParams{}
	if input.Name != nil {
		trimmed := strings.TrimSpace(*input.Name)
		params.Name = &trimmed
	}
	if input.ShortDescription != nil {
		trimmed := strings.TrimSpace(*input.ShortDescription)
		params.ShortDescription = &trimmed
	}
	if input.LongDescription != nil {
		trimmed := strings.TrimSpace(*input.LongDescription)
		params.LongDescription = &trimmed
	}
	if input.HowToPlay != nil {
		trimmed := strings.TrimSpace(*input.HowToPlay)
		params.HowToPlay = &trimmed
	}
	if input.Tags != nil {
		if err := developer.ValidateCatalogTags(input.Tags); err != nil {
			return nil, err
		}
		params.Tags = input.Tags
	}
	if input.ContactEmail != nil {
		trimmed := strings.TrimSpace(*input.ContactEmail)
		params.ContactEmail = &trimmed
	}
	if input.WebsiteURL != nil {
		trimmed := strings.TrimSpace(*input.WebsiteURL)
		if trimmed == "" {
			params.ClearWebsite = true
		} else {
			params.WebsiteURL = &trimmed
		}
	}
	if input.CommunityURL != nil {
		trimmed := strings.TrimSpace(*input.CommunityURL)
		if trimmed == "" {
			params.ClearCommunity = true
		} else {
			params.CommunityURL = &trimmed
		}
	}

	game, err := st.UpdateMyGameMetadata(ctx, gameID, userID, params)
	if err != nil {
		return nil, err
	}
	return ToGraphQLGame(game), nil
}

// RequestPublicRelease is the resolver for the requestPublicRelease field.
func (r *mutationResolver) RequestPublicRelease(ctx context.Context, gameID string) (*model.Game, error) {
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	id, err := parseUUID(gameID, "game id")
	if err != nil {
		return nil, err
	}
	game, err := st.RequestPublicRelease(ctx, id, userID)
	if err != nil {
		return nil, err
	}
	return ToGraphQLGame(game), nil
}

// ReviewGameRelease is the resolver for the reviewGameRelease field.
func (r *mutationResolver) ReviewGameRelease(ctx context.Context, gameID string, approve bool, reason *string) (*model.Game, error) {
	if _, err := r.requireAdmin(ctx); err != nil {
		return nil, err
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	id, err := parseUUID(gameID, "game id")
	if err != nil {
		return nil, err
	}
	game, err := st.ReviewGameRelease(ctx, id, approve)
	if err != nil {
		return nil, err
	}
	_ = reason // email notification is follow-up work
	return ToGraphQLGame(game), nil
}

// MyGames is the resolver for the myGames field.
func (r *queryResolver) MyGames(ctx context.Context) ([]*model.Game, error) {
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	games, err := st.ListMyGames(ctx, userID)
	if err != nil {
		return nil, err
	}
	return ToGraphQLGames(games), nil
}

// MyGame is the resolver for the myGame field.
func (r *queryResolver) MyGame(ctx context.Context, id string) (*model.Game, error) {
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	gameID, err := parseUUID(id, "game id")
	if err != nil {
		return nil, err
	}
	game, err := st.GetOwnedGame(ctx, gameID, userID)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return ToGraphQLGame(game), nil
}

// MyGameCredentials is the resolver for the myGameCredentials field.
func (r *queryResolver) MyGameCredentials(ctx context.Context, id string) (*model.MyGameCredentials, error) {
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	gameID, err := parseUUID(id, "game id")
	if err != nil {
		return nil, err
	}
	game, err := st.GetOwnedGame(ctx, gameID, userID)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}
	serviceToken, err := auth.FormatGameServiceToken(game.ID)
	if err != nil {
		return nil, err
	}
	secret := ""
	if game.WebhookSecret != nil {
		secret = *game.WebhookSecret
	}
	return &model.MyGameCredentials{
		ServiceToken:  serviceToken,
		WebhookSecret: secret,
	}, nil
}

// MyDeveloperAPIKeys is the resolver for the myDeveloperApiKeys field.
func (r *queryResolver) MyDeveloperAPIKeys(ctx context.Context) ([]*model.DeveloperAPIKey, error) {
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	keys, err := st.ListDeveloperAPIKeys(ctx, userID)
	if err != nil {
		return nil, err
	}
	out := make([]*model.DeveloperAPIKey, len(keys))
	for i := range keys {
		out[i] = ToGraphQLDeveloperAPIKey(&keys[i])
	}
	return out, nil
}

// DeveloperIntegrationGuide is the resolver for the developerIntegrationGuide field.
func (r *queryResolver) DeveloperIntegrationGuide(ctx context.Context) (string, error) {
	return developer.IntegrationGuide(), nil
}

// DeveloperAgentPlaybook is the resolver for the developerAgentPlaybook field.
func (r *queryResolver) DeveloperAgentPlaybook(ctx context.Context) (string, error) {
	return developer.AgentPlaybook(), nil
}

// DeveloperDiscoveryPrompt is the resolver for the developerDiscoveryPrompt field.
func (r *queryResolver) DeveloperDiscoveryPrompt(ctx context.Context) (string, error) {
	return developer.DiscoveryPrompt(), nil
}

// CatalogTagTaxonomy is the resolver for the catalogTagTaxonomy field.
func (r *queryResolver) CatalogTagTaxonomy(ctx context.Context) ([]*model.CatalogTagOption, error) {
	out := make([]*model.CatalogTagOption, len(developer.CatalogTagTaxonomy))
	for i, tag := range developer.CatalogTagTaxonomy {
		out[i] = &model.CatalogTagOption{
			ID:          tag.ID,
			Label:       tag.Label,
			Description: tag.Description,
		}
	}
	return out, nil
}

// PendingGameReviews is the resolver for the pendingGameReviews field.
func (r *queryResolver) PendingGameReviews(ctx context.Context) ([]*model.Game, error) {
	if _, err := r.requireAdmin(ctx); err != nil {
		return nil, err
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	games, err := st.ListPendingGameReviews(ctx)
	if err != nil {
		return nil, err
	}
	return ToGraphQLGames(games), nil
}
