package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"errors"
	"fmt"

	"github.com/scruffyprodigy/playhub/graph/generated"
	"github.com/scruffyprodigy/playhub/graph/model"
	"github.com/scruffyprodigy/playhub/internal/store"
)

// FormingGaps is the resolver for the formingGaps field.
func (r *activeIntentResolver) FormingGaps(ctx context.Context, obj *model.ActiveIntent) ([]*model.QueuePathGap, error) {
	if obj == nil || obj.Status != model.QueueStatusWaiting || obj.QueueID == nil {
		return []*model.QueuePathGap{}, nil
	}
	modeQueueID, err := parseUUID(*obj.QueueID, "queue id")
	if err != nil {
		return nil, err
	}
	gaps, err := r.formingGapsForModeQueue(ctx, modeQueueID)
	if err != nil {
		return []*model.QueuePathGap{}, nil
	}
	return gaps, nil
}

// ActiveSessions is the resolver for the activeSessions field.
func (r *gameResolver) ActiveSessions(ctx context.Context, obj *model.Game, limit *int) ([]*model.Session, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}

	gameID, err := parseUUID(obj.ID, "game id")
	if err != nil {
		return nil, err
	}

	pageSize := 10
	if limit != nil {
		pageSize = *limit
	}

	sessions, err := st.ListActiveSessionsByGame(ctx, gameID, pageSize)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Session, len(sessions))
	for i := range sessions {
		result[i] = ToGraphQLSession(&sessions[i], nil)
	}
	return result, nil
}

// Game is the resolver for the game field.
func (r *sessionResolver) Game(ctx context.Context, obj *model.Session) (*model.Game, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}

	sessionID, err := parseUUID(obj.ID, "session id")
	if err != nil {
		return nil, err
	}

	session, err := st.GetSessionByID(ctx, sessionID)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return nil, fmt.Errorf("session not found")
		}
		return nil, err
	}

	game, err := st.GetGameByID(ctx, session.GameID)
	if err != nil {
		return nil, err
	}

	return ToGraphQLGame(game), nil
}

// Players is the resolver for the players field.
func (r *sessionResolver) Players(ctx context.Context, obj *model.Session) ([]*model.User, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}

	sessionID, err := parseUUID(obj.ID, "session id")
	if err != nil {
		return nil, err
	}

	users, err := st.ListSessionParticipants(ctx, sessionID)
	if err != nil {
		return nil, err
	}

	return ToGraphQLUsers(users), nil
}

// ActiveIntent returns generated.ActiveIntentResolver implementation.
func (r *Resolver) ActiveIntent() generated.ActiveIntentResolver { return &activeIntentResolver{r} }

// Game returns generated.GameResolver implementation.
func (r *Resolver) Game() generated.GameResolver { return &gameResolver{r} }

// Session returns generated.SessionResolver implementation.
func (r *Resolver) Session() generated.SessionResolver { return &sessionResolver{r} }

type activeIntentResolver struct{ *Resolver }
type gameResolver struct{ *Resolver }
type sessionResolver struct{ *Resolver }
