package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"errors"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/scruffyprodigy/playhub/graph/model"
	"github.com/scruffyprodigy/playhub/internal/store"
)

func loadAuthorizedGameSession(ctx context.Context, st *store.Store, matchID string) (uuid.UUID, *store.Session, error) {
	sessionID, err := parseUUID(matchID, "match id")
	if err != nil {
		return uuid.Nil, nil, err
	}
	session, err := st.GetSessionByID(ctx, sessionID)
	if err != nil {
		return uuid.Nil, nil, err
	}
	if err := requireGameServiceForSessionGame(ctx, session.GameID); err != nil {
		return uuid.Nil, nil, err
	}
	return sessionID, session, nil
}

func returnDestinationFromContext(ctx store.ReturnContext) *model.ReturnDestination {
	defaultDest := &model.ReturnDestination{Path: "/", Kind: store.ReturnKindCatalogLFG}
	if err := ctx.Validate(); err != nil {
		return defaultDest
	}
	return &model.ReturnDestination{Path: ctx.Path, Kind: ctx.Kind}
}

// ReportPlayerFinished is the resolver for the reportPlayerFinished field.
func (r *mutationResolver) ReportPlayerFinished(ctx context.Context, matchID string, lobbyUserID string, reason model.PlayerFinishReason, placement *int, metadata map[string]any) (bool, error) {
	if err := requireGameServiceAuth(ctx); err != nil {
		return false, err
	}
	st, err := r.requireStore()
	if err != nil {
		return false, err
	}

	sessionID, session, err := loadAuthorizedGameSession(ctx, st, matchID)
	if err != nil {
		return false, err
	}
	playerID, err := parseUUID(lobbyUserID, "lobby user id")
	if err != nil {
		return false, err
	}

	now := time.Now()
	if err := st.MarkParticipantFinished(ctx, sessionID, playerID, now); err != nil {
		return false, err
	}
	if session.ModeQueueID != nil {
		if err := st.ReleaseUserMatchedQueue(ctx, *session.ModeQueueID, playerID); err != nil {
			return false, err
		}
	}

	remaining, err := st.CountActiveParticipants(ctx, sessionID)
	if err != nil {
		return false, err
	}
	if remaining == 0 {
		if err := st.CompleteSession(ctx, sessionID, now); err != nil && !errors.Is(err, store.ErrNotFound) {
			return false, err
		}
	}

	_ = reason
	_ = placement
	_ = metadata
	return true, nil
}

// ReportMatchResult is the resolver for the reportMatchResult field.
func (r *mutationResolver) ReportMatchResult(ctx context.Context, matchID string, status model.MatchResultStatus, winnerLobbyUserIds []string, metadata map[string]any) (bool, error) {
	if err := requireGameServiceAuth(ctx); err != nil {
		return false, err
	}
	st, err := r.requireStore()
	if err != nil {
		return false, err
	}

	sessionID, _, err := loadAuthorizedGameSession(ctx, st, matchID)
	if err != nil {
		return false, err
	}

	if err := st.CompleteSession(ctx, sessionID, time.Now()); err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return true, nil
		}
		return false, err
	}

	_ = status
	_ = winnerLobbyUserIds
	_ = metadata
	return true, nil
}

// ReturnDestination is the resolver for the returnDestination field.
func (r *queryResolver) ReturnDestination(ctx context.Context, matchID *string) (*model.ReturnDestination, error) {
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}

	defaultDest := &model.ReturnDestination{Path: "/", Kind: store.ReturnKindCatalogLFG}

	var sessionID uuid.UUID
	if matchID != nil && strings.TrimSpace(*matchID) != "" {
		sessionID, err = parseUUID(strings.TrimSpace(*matchID), "match id")
		if err != nil {
			return nil, err
		}
	} else {
		view, vErr := st.GetUserActiveQueue(ctx, userID)
		if vErr != nil {
			return nil, vErr
		}
		if view == nil || !view.Matched || view.SessionID == nil {
			return defaultDest, nil
		}
		sessionID = *view.SessionID
	}

	if err := st.AcknowledgePlayerReturn(ctx, sessionID, userID, time.Now()); err != nil && !errors.Is(err, store.ErrNotFound) {
		return nil, err
	}

	if err := st.ParticipantIsActive(ctx, sessionID, userID); err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return defaultDest, nil
		}
		return nil, err
	}

	ctxData, err := st.GetParticipantReturnContext(ctx, sessionID, userID)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return defaultDest, nil
		}
		return nil, err
	}
	return returnDestinationFromContext(ctxData), nil
}
