package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/google/uuid"
	"github.com/scruffyprodigy/playhub/graph/generated"
	"github.com/scruffyprodigy/playhub/graph/model"
	"github.com/scruffyprodigy/playhub/internal/pubsub"
	"github.com/scruffyprodigy/playhub/internal/store"
)

// CreateRoom is the resolver for the createRoom field.
func (r *mutationResolver) CreateRoom(ctx context.Context) (*model.Room, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	room, err := st.CreateRoom(ctx, userID)
	if err != nil {
		return nil, err
	}
	return r.roomAfterMutation(ctx, room)
}

// JoinRoom is the resolver for the joinRoom field.
func (r *mutationResolver) JoinRoom(ctx context.Context, inviteCode string) (*model.Room, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	room, err := st.JoinRoom(ctx, userID, inviteCode)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return nil, fmt.Errorf("room not found")
		}
		return nil, err
	}
	return r.roomAfterMutation(ctx, room)
}

// LeaveRoom is the resolver for the leaveRoom field.
func (r *mutationResolver) LeaveRoom(ctx context.Context) (bool, error) {
	st, err := r.requireStore()
	if err != nil {
		return false, err
	}
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return false, err
	}
	room, err := st.GetUserRoom(ctx, userID)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return false, nil
		}
		return false, err
	}
	left, err := st.LeaveRoom(ctx, userID)
	if err != nil {
		return false, err
	}
	if left {
		if err := r.publishRoomUpdated(ctx, room.ID); err != nil {
			return false, err
		}
	}
	return left, nil
}

// SendRoomMessage is the resolver for the sendRoomMessage field.
func (r *mutationResolver) SendRoomMessage(ctx context.Context, roomID string, body string) (*model.RoomMessage, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	rid, err := parseUUID(roomID, "room id")
	if err != nil {
		return nil, err
	}
	msg, err := st.SendRoomMessage(ctx, rid, userID, body)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return nil, fmt.Errorf("not a member of this room")
		}
		return nil, err
	}
	if err := r.publishRoomMessage(ctx, rid, msg.ID); err != nil {
		return nil, err
	}
	return toGraphQLRoomMessage(msg), nil
}

// Room is the resolver for the room field.
func (r *queryResolver) Room(ctx context.Context, inviteCode string) (*model.Room, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	room, err := st.GetRoomByInviteCode(ctx, inviteCode)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}
	if err := r.requireRoomMember(ctx, room.ID, userID); err != nil {
		return nil, nil
	}
	return toGraphQLRoom(room), nil
}

// MyRoom is the resolver for the myRoom field.
func (r *queryResolver) MyRoom(ctx context.Context) (*model.Room, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	room, err := st.GetUserRoom(ctx, userID)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return toGraphQLRoom(room), nil
}

// JoinURL is the resolver for the joinUrl field.
func (r *roomResolver) JoinURL(ctx context.Context, obj *model.Room) (string, error) {
	if obj == nil {
		return "", fmt.Errorf("room is required")
	}
	return roomJoinURL(obj.InviteCode), nil
}

// Host is the resolver for the host field.
func (r *roomResolver) Host(ctx context.Context, obj *model.Room) (*model.User, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	roomID, err := parseUUID(obj.ID, "room id")
	if err != nil {
		return nil, err
	}
	room, err := st.GetRoomByID(ctx, roomID)
	if err != nil {
		return nil, err
	}
	user, err := st.GetUserByID(ctx, room.HostUserID)
	if err != nil {
		return nil, err
	}
	return ToGraphQLUser(user), nil
}

// Members is the resolver for the members field.
func (r *roomResolver) Members(ctx context.Context, obj *model.Room) ([]*model.User, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	roomID, err := parseUUID(obj.ID, "room id")
	if err != nil {
		return nil, err
	}
	users, err := st.ListRoomMemberUsers(ctx, roomID)
	if err != nil {
		return nil, err
	}
	return ToGraphQLUsers(users), nil
}

// Messages is the resolver for the messages field.
func (r *roomResolver) Messages(ctx context.Context, obj *model.Room, limit *int, before *string) ([]*model.RoomMessage, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	roomID, err := parseUUID(obj.ID, "room id")
	if err != nil {
		return nil, err
	}
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	if err := r.requireRoomMember(ctx, roomID, userID); err != nil {
		return nil, err
	}

	lim := 50
	if limit != nil {
		lim = *limit
	}
	var beforeID *uuid.UUID
	if before != nil && strings.TrimSpace(*before) != "" {
		id, err := parseUUID(*before, "message id")
		if err != nil {
			return nil, err
		}
		beforeID = &id
	}

	msgs, err := st.ListRoomMessages(ctx, roomID, lim, beforeID)
	if err != nil {
		return nil, err
	}
	out := make([]*model.RoomMessage, len(msgs))
	for i := range msgs {
		out[i] = toGraphQLRoomMessage(&msgs[i])
	}
	return out, nil
}

// Author is the resolver for the author field.
func (r *roomMessageResolver) Author(ctx context.Context, obj *model.RoomMessage) (*model.User, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	msgID, err := parseUUID(obj.ID, "message id")
	if err != nil {
		return nil, err
	}
	msg, err := st.GetRoomMessageByID(ctx, msgID)
	if err != nil {
		return nil, err
	}
	user, err := st.GetUserByID(ctx, msg.UserID)
	if err != nil {
		return nil, err
	}
	return ToGraphQLUser(user), nil
}

// RoomUpdated is the resolver for the roomUpdated field.
func (r *subscriptionResolver) RoomUpdated(ctx context.Context, roomID string) (<-chan *model.Room, error) {
	if r.PubSub == nil {
		return nil, fmt.Errorf("pubsub is not configured")
	}
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	rid, err := parseUUID(roomID, "room id")
	if err != nil {
		return nil, err
	}
	if err := r.requireRoomMember(ctx, rid, userID); err != nil {
		return nil, err
	}

	initial, err := r.loadRoomModel(ctx, rid)
	if err != nil {
		return nil, err
	}

	messages, unsubscribe, err := r.PubSub.Subscribe(ctx, pubsub.RoomChannel(roomID))
	if err != nil {
		return nil, err
	}

	updates := make(chan *model.Room, 4)
	go func() {
		defer close(updates)
		defer unsubscribe()

		if initial != nil {
			select {
			case updates <- initial:
			case <-ctx.Done():
				return
			}
		}

		for {
			select {
			case <-ctx.Done():
				return
			case payload, ok := <-messages:
				if !ok {
					return
				}
				event, err := pubsub.UnmarshalRoomEvent(payload)
				if err != nil || event.Type != pubsub.RoomEventUpdated {
					continue
				}
				room, err := r.loadRoomModel(ctx, rid)
				if err != nil {
					continue
				}
				select {
				case updates <- room:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return updates, nil
}

// RoomMessageAdded is the resolver for the roomMessageAdded field.
func (r *subscriptionResolver) RoomMessageAdded(ctx context.Context, roomID string) (<-chan *model.RoomMessage, error) {
	if r.PubSub == nil {
		return nil, fmt.Errorf("pubsub is not configured")
	}
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	rid, err := parseUUID(roomID, "room id")
	if err != nil {
		return nil, err
	}
	if err := r.requireRoomMember(ctx, rid, userID); err != nil {
		return nil, err
	}

	messages, unsubscribe, err := r.PubSub.Subscribe(ctx, pubsub.RoomChannel(roomID))
	if err != nil {
		return nil, err
	}

	updates := make(chan *model.RoomMessage, 8)
	go func() {
		defer close(updates)
		defer unsubscribe()

		for {
			select {
			case <-ctx.Done():
				return
			case payload, ok := <-messages:
				if !ok {
					return
				}
				event, err := pubsub.UnmarshalRoomEvent(payload)
				if err != nil || event.Type != pubsub.RoomEventMessage || event.MessageID == "" {
					continue
				}
				msgID, err := parseUUID(event.MessageID, "message id")
				if err != nil {
					continue
				}
				msg, err := st.GetRoomMessageByID(ctx, msgID)
				if err != nil {
					continue
				}
				select {
				case updates <- toGraphQLRoomMessage(msg):
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return updates, nil
}

// Room returns generated.RoomResolver implementation.
func (r *Resolver) Room() generated.RoomResolver { return &roomResolver{r} }

// RoomMessage returns generated.RoomMessageResolver implementation.
func (r *Resolver) RoomMessage() generated.RoomMessageResolver { return &roomMessageResolver{r} }

type roomResolver struct{ *Resolver }
type roomMessageResolver struct{ *Resolver }
