package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/scruffyprodigy/playhub/graph/model"
	"github.com/scruffyprodigy/playhub/internal/spiritanimal"
	"github.com/scruffyprodigy/playhub/internal/store"
)

// BeginSpiritAnimalReading is the resolver for the beginSpiritAnimalReading field.
func (r *mutationResolver) BeginSpiritAnimalReading(ctx context.Context, forceRestart *bool) (*model.SpiritAnimalReading, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	runner, err := r.requireSpiritAnimalRunner()
	if err != nil {
		return nil, err
	}
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}

	restart := forceRestart != nil && *forceRestart
	if existing, err := st.GetActiveAvatarReadingForUser(ctx, userID); err == nil {
		if existing.Status == store.ReadingStatusFailed && !restart {
			return graphQLSpiritAnimalReading(runner, existing)
		}
		if !restart {
			runner.MaybeResumeReading(ctx, existing)
			return graphQLSpiritAnimalReading(runner, existing)
		}
		if err := st.ArchiveAvatarReading(ctx, existing.ID); err != nil {
			return nil, err
		}
	} else if !errors.Is(err, store.ErrReadingNotFound) {
		return nil, err
	}

	user, err := st.GetUserByID(ctx, userID)
	if err != nil {
		return nil, err
	}
	if err := ensureSpiritAnimalJourneyAllowed(ctx, st, user); err != nil {
		return nil, err
	}
	if err := ensureSpiritAnimalStartAllowed(ctx, st, userID); err != nil {
		return nil, err
	}

	draw, err := spiritanimal.DrawCards()
	if err != nil {
		return nil, err
	}
	reading, err := st.CreateAvatarReading(ctx, userID, draw)
	if err != nil {
		return nil, err
	}

	readingID := reading.ID
	go runner.GenerateQuestions(context.Background(), readingID)

	return graphQLSpiritAnimalReading(runner, reading)
}

// SubmitSpiritAnimalAnswers is the resolver for the submitSpiritAnimalAnswers field.
func (r *mutationResolver) SubmitSpiritAnimalAnswers(ctx context.Context, answers []string) (*model.SpiritAnimalReading, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	runner, err := r.requireSpiritAnimalRunner()
	if err != nil {
		return nil, err
	}
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}

	reading, err := st.GetActiveAvatarReadingForUser(ctx, userID)
	if err != nil {
		return nil, err
	}
	if reading.Status != store.ReadingStatusAwaitingAnswers {
		return nil, fmt.Errorf("reading is not awaiting answers")
	}

	normalized := make([]string, len(answers))
	for i, answer := range answers {
		normalized[i] = strings.ToUpper(strings.TrimSpace(answer))
	}
	if err := spiritanimal.ValidateSubmittedAnswers(reading.QuestionsJSON, normalized); err != nil {
		return nil, err
	}

	reading, err = st.SaveAvatarReadingAnswers(ctx, reading.ID, normalized)
	if err != nil {
		return nil, err
	}

	readingID := reading.ID
	go runner.ProcessAnswers(context.Background(), readingID)

	return graphQLSpiritAnimalReading(runner, reading)
}

// RegenerateSpiritAnimalImages is the resolver for the regenerateSpiritAnimalImages field.
func (r *mutationResolver) RegenerateSpiritAnimalImages(ctx context.Context) (*model.SpiritAnimalReading, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	runner, err := r.requireSpiritAnimalRunner()
	if err != nil {
		return nil, err
	}
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}

	reading, err := st.GetActiveAvatarReadingForUser(ctx, userID)
	if err != nil {
		return nil, err
	}
	if reading.Status != store.ReadingStatusReady {
		return nil, fmt.Errorf("reading is not ready for image regeneration")
	}
	if !runner.ImagesMissingForReading(reading) {
		return graphQLSpiritAnimalReading(runner, reading)
	}

	reading, err = st.UpdateAvatarReadingStatus(ctx, reading.ID, store.ReadingStatusProcessing, nil)
	if err != nil {
		return nil, err
	}

	readingID := reading.ID
	go runner.RegenerateTotemImages(context.Background(), readingID)

	return graphQLSpiritAnimalReading(runner, reading)
}

// SelectSpiritAnimalTotem is the resolver for the selectSpiritAnimalTotem field.
func (r *mutationResolver) SelectSpiritAnimalTotem(ctx context.Context, totemName string) (*model.User, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}

	reading, err := st.GetActiveAvatarReadingForUser(ctx, userID)
	if err != nil {
		return nil, err
	}
	if reading.Status != store.ReadingStatusReady {
		return nil, fmt.Errorf("reading is not ready for selection")
	}

	imageURL, err := spiritAnimalTotemImageURL(reading, totemName)
	if err != nil {
		return nil, err
	}

	user, err := st.SelectSpiritAnimalTotem(ctx, userID, reading.ID, totemName, imageURL)
	if err != nil {
		return nil, err
	}
	return ToGraphQLUser(user), nil
}

// MySpiritAnimalReading is the resolver for the mySpiritAnimalReading field.
func (r *queryResolver) MySpiritAnimalReading(ctx context.Context) (*model.SpiritAnimalReading, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	runner, err := r.requireSpiritAnimalRunner()
	if err != nil {
		return nil, err
	}
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	reading, err := st.GetActiveAvatarReadingForUser(ctx, userID)
	if errors.Is(err, store.ErrReadingNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	runner.MaybeResumeReading(ctx, reading)
	return graphQLSpiritAnimalReading(runner, reading)
}

// MySpiritAnimalJourneyEligibility is the resolver for the mySpiritAnimalJourneyEligibility field.
func (r *queryResolver) MySpiritAnimalJourneyEligibility(ctx context.Context) (*model.SpiritAnimalJourneyEligibility, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	user, err := st.GetUserByID(ctx, userID)
	if err != nil {
		return nil, err
	}
	return spiritAnimalJourneyEligibility(ctx, st, user)
}
