package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"errors"
	"fmt"

	"github.com/google/uuid"
	"github.com/scruffyprodigy/playhub/graph/generated"
	"github.com/scruffyprodigy/playhub/graph/model"
	"github.com/scruffyprodigy/playhub/internal/pubsub"
	"github.com/scruffyprodigy/playhub/internal/store"
)

// CreatePrivateTable is the resolver for the createPrivateTable field.
func (r *mutationResolver) CreatePrivateTable(ctx context.Context, gameID string, modeID string) (*model.Table, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	gid, err := parseUUID(gameID, "game id")
	if err != nil {
		return nil, err
	}
	mid, err := parseUUID(modeID, "mode id")
	if err != nil {
		return nil, err
	}
	table, err := st.CreatePrivateTable(ctx, userID, gid, mid)
	if err != nil {
		return nil, err
	}
	return r.tableAfterMutation(ctx, table)
}

// CreateTable is the resolver for the createTable field.
func (r *mutationResolver) CreateTable(ctx context.Context, roomID string, gameID string, modeID string) (*model.Table, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	rid, err := parseUUID(roomID, "room id")
	if err != nil {
		return nil, err
	}
	gid, err := parseUUID(gameID, "game id")
	if err != nil {
		return nil, err
	}
	mid, err := parseUUID(modeID, "mode id")
	if err != nil {
		return nil, err
	}
	table, err := st.CreateTable(ctx, rid, gid, mid, userID)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return nil, fmt.Errorf("not a member of this room")
		}
		return nil, err
	}
	return r.tableAfterMutation(ctx, table)
}

// SitAtTable is the resolver for the sitAtTable field.
func (r *mutationResolver) SitAtTable(ctx context.Context, tableID string, seatKey string) (*model.Table, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	tid, err := parseUUID(tableID, "table id")
	if err != nil {
		return nil, err
	}
	if _, err := r.requireTableRoomMember(ctx, tid, userID); err != nil {
		return nil, err
	}
	table, err := st.SitAtTable(ctx, tid, userID, seatKey)
	if err != nil {
		if errors.Is(err, store.ErrAlreadyMatched) {
			return nil, fmt.Errorf("leave your active match before sitting at a table")
		}
		return nil, err
	}
	return r.tableAfterMutation(ctx, table)
}

// LeaveTable is the resolver for the leaveTable field.
func (r *mutationResolver) LeaveTable(ctx context.Context, tableID string) (bool, error) {
	st, err := r.requireStore()
	if err != nil {
		return false, err
	}
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return false, err
	}
	tid, err := parseUUID(tableID, "table id")
	if err != nil {
		return false, err
	}
	table, err := r.requireTableRoomMember(ctx, tid, userID)
	if err != nil {
		return false, err
	}
	left, err := st.LeaveTable(ctx, tid, userID)
	if err != nil {
		return false, err
	}
	if left {
		if err := r.publishTableUpdated(ctx, table.RoomID, tid); err != nil {
			return false, err
		}
	}
	return left, nil
}

// DiscardTable is the resolver for the discardTable field.
func (r *mutationResolver) DiscardTable(ctx context.Context, tableID string) (bool, error) {
	st, err := r.requireStore()
	if err != nil {
		return false, err
	}
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return false, err
	}
	tid, err := parseUUID(tableID, "table id")
	if err != nil {
		return false, err
	}
	table, err := r.requireTableRoomMember(ctx, tid, userID)
	if err != nil {
		return false, err
	}
	discarded, err := st.DiscardTable(ctx, tid, userID)
	if err != nil {
		return false, err
	}
	if discarded {
		if err := r.publishTableUpdated(ctx, table.RoomID, tid); err != nil {
			return false, err
		}
	}
	return discarded, nil
}

// StartTable is the resolver for the startTable field.
func (r *mutationResolver) StartTable(ctx context.Context, tableID string) (*model.JoinResult, error) {
	tid, err := parseUUID(tableID, "table id")
	if err != nil {
		return nil, err
	}
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	if _, err := r.requireTableRoomMember(ctx, tid, userID); err != nil {
		return nil, err
	}
	return r.startTableInternal(ctx, tid)
}

// StartTableBackfill is the resolver for the startTableBackfill field.
func (r *mutationResolver) StartTableBackfill(ctx context.Context, tableID string, queueID string) (*model.JoinResult, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	tid, err := parseUUID(tableID, "table id")
	if err != nil {
		return nil, err
	}
	qid, err := parseUUID(queueID, "queue id")
	if err != nil {
		return nil, err
	}
	table, err := r.requireTableRoomMember(ctx, tid, userID)
	if err != nil {
		return nil, err
	}
	_ = table

	result, err := st.StartTableBackfill(ctx, tid, userID, qid)
	if err != nil {
		return nil, err
	}

	var launchURLs map[uuid.UUID]string
	if result.Status == store.QueueStatusMatched && result.SessionID != nil {
		game, gErr := st.GetGameByID(ctx, result.GameID)
		if gErr != nil {
			return nil, gErr
		}
		launchURLs, err = r.finalizeMatchedSession(ctx, game, *result.SessionID, result.NotifyUserIDs)
		if err != nil {
			return nil, err
		}
		if err := r.publishTableSeatStarted(ctx, tid, result.NotifyUserIDs, launchURLs); err != nil {
			return nil, err
		}
		if err := r.publishTableUpdated(ctx, table.RoomID, tid); err != nil {
			return nil, err
		}
	} else if err := r.publishTableUpdated(ctx, table.RoomID, tid); err != nil {
		return nil, err
	}

	if err := r.publishQueueResult(ctx, result, launchURLs); err != nil {
		return nil, err
	}

	queued := result.Status == store.QueueStatusWaiting
	joinResult := &model.JoinResult{Queued: queued}
	if result.QueuedCount > 0 {
		count := result.QueuedCount
		joinResult.QueuedCount = &count
	}
	if result.SessionID != nil {
		id := result.SessionID.String()
		joinResult.SessionID = &id
		if launch := launchURLs[userID]; launch != "" {
			joinResult.JoinURL = &launch
		}
	}
	return joinResult, nil
}

// BackfillActive is the resolver for the backfillActive field.
func (r *myTableSeatResolver) BackfillActive(ctx context.Context, obj *model.MyTableSeat) (bool, error) {
	if obj == nil || obj.Status == "started" {
		return false, nil
	}
	_, active, err := r.resolveTableSeatGaps(ctx, obj.TableID)
	return active, err
}

// FormingGaps is the resolver for the formingGaps field.
func (r *myTableSeatResolver) FormingGaps(ctx context.Context, obj *model.MyTableSeat) ([]*model.QueuePathGap, error) {
	if obj == nil || obj.Status == "started" {
		return []*model.QueuePathGap{}, nil
	}
	gaps, _, err := r.resolveTableSeatGaps(ctx, obj.TableID)
	return gaps, err
}

// MyTableSeat is the resolver for the myTableSeat field.
func (r *queryResolver) MyTableSeat(ctx context.Context) (*model.MyTableSeat, error) {
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	return r.resolveMyTableSeat(ctx, userID)
}

// Tables is the resolver for the tables field.
func (r *roomResolver) Tables(ctx context.Context, obj *model.Room) ([]*model.Table, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	roomID, err := parseUUID(obj.ID, "room id")
	if err != nil {
		return nil, err
	}
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	if err := r.requireRoomMember(ctx, roomID, userID); err != nil {
		return nil, err
	}
	tables, err := st.ListRoomTables(ctx, roomID)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Table, len(tables))
	for i := range tables {
		out[i] = toGraphQLTable(&tables[i])
	}
	return out, nil
}

// TableUpdated is the resolver for the tableUpdated field.
func (r *subscriptionResolver) TableUpdated(ctx context.Context, roomID string) (<-chan *model.Table, error) {
	if r.PubSub == nil {
		return nil, fmt.Errorf("pubsub is not configured")
	}
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return nil, err
	}
	rid, err := parseUUID(roomID, "room id")
	if err != nil {
		return nil, err
	}
	if err := r.requireRoomMember(ctx, rid, userID); err != nil {
		return nil, err
	}

	messages, unsubscribe, err := r.PubSub.Subscribe(ctx, pubsub.RoomChannel(roomID))
	if err != nil {
		return nil, err
	}

	updates := make(chan *model.Table, 8)
	go func() {
		defer close(updates)
		defer unsubscribe()

		for {
			select {
			case <-ctx.Done():
				return
			case payload, ok := <-messages:
				if !ok {
					return
				}
				event, err := pubsub.UnmarshalRoomEvent(payload)
				if err != nil || event.Type != pubsub.RoomEventTableUpdated || event.TableID == "" {
					continue
				}
				tableID, err := parseUUID(event.TableID, "table id")
				if err != nil {
					continue
				}
				table, err := r.loadTableModel(ctx, tableID)
				if err != nil {
					continue
				}
				select {
				case updates <- table:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return updates, nil
}

// MyTableSeatUpdated is the resolver for the myTableSeatUpdated field.
func (r *subscriptionResolver) MyTableSeatUpdated(ctx context.Context) (<-chan *model.MyTableSeat, error) {
	return r.myTableSeatUpdatedSubscription(ctx)
}

// Game is the resolver for the game field.
func (r *tableResolver) Game(ctx context.Context, obj *model.Table) (*model.Game, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	tableID, err := tableRoomIDFromObj(obj)
	if err != nil {
		return nil, err
	}
	table, err := st.GetRoomTableByID(ctx, tableID)
	if err != nil {
		return nil, err
	}
	game, err := st.GetGameByID(ctx, table.GameID)
	if err != nil {
		return nil, err
	}
	return ToGraphQLGame(game), nil
}

// Mode is the resolver for the mode field.
func (r *tableResolver) Mode(ctx context.Context, obj *model.Table) (*model.GameMode, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	tableID, err := tableRoomIDFromObj(obj)
	if err != nil {
		return nil, err
	}
	table, err := st.GetRoomTableByID(ctx, tableID)
	if err != nil {
		return nil, err
	}
	mode, err := st.GetGameModeByID(ctx, table.ModeID)
	if err != nil {
		return nil, err
	}
	return ToGraphQLGameMode(mode), nil
}

// King is the resolver for the king field.
func (r *tableResolver) King(ctx context.Context, obj *model.Table) (*model.User, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	tableID, err := tableRoomIDFromObj(obj)
	if err != nil {
		return nil, err
	}
	kingID, err := st.TableKingUserID(ctx, tableID)
	if err != nil {
		return nil, err
	}
	if kingID == nil {
		return nil, nil
	}
	user, err := st.GetUserByID(ctx, *kingID)
	if err != nil {
		return nil, err
	}
	return ToGraphQLUser(user), nil
}

// Seats is the resolver for the seats field.
func (r *tableResolver) Seats(ctx context.Context, obj *model.Table) ([]*model.TableSeat, error) {
	st, err := r.requireStore()
	if err != nil {
		return nil, err
	}
	tableID, err := tableRoomIDFromObj(obj)
	if err != nil {
		return nil, err
	}
	seated, err := st.ListTableSeats(ctx, tableID)
	if err != nil {
		return nil, err
	}
	out := make([]*model.TableSeat, len(seated))
	for i, seat := range seated {
		out[i] = &model.TableSeat{
			SeatKey:  seat.SeatKey,
			SeatedAt: seat.SeatedAt,
		}
		user, uErr := st.GetUserByID(ctx, seat.UserID)
		if uErr == nil {
			out[i].User = ToGraphQLUser(user)
		}
	}
	return out, nil
}

// SeatSlots is the resolver for the seatSlots field.
func (r *tableResolver) SeatSlots(ctx context.Context, obj *model.Table) ([]*model.TableSeatSlot, error) {
	tableID, err := tableRoomIDFromObj(obj)
	if err != nil {
		return nil, err
	}
	return r.buildTableSeatSlots(ctx, tableID)
}

// CanStart is the resolver for the canStart field.
func (r *tableResolver) CanStart(ctx context.Context, obj *model.Table) (bool, error) {
	st, err := r.requireStore()
	if err != nil {
		return false, err
	}
	tableID, err := tableRoomIDFromObj(obj)
	if err != nil {
		return false, err
	}
	return st.TableCanStart(ctx, tableID)
}

// CanDiscard is the resolver for the canDiscard field.
func (r *tableResolver) CanDiscard(ctx context.Context, obj *model.Table) (bool, error) {
	st, err := r.requireStore()
	if err != nil {
		return false, err
	}
	userID, err := requireAuthUserID(ctx)
	if err != nil {
		return false, err
	}
	tableID, err := tableRoomIDFromObj(obj)
	if err != nil {
		return false, err
	}
	return st.TableCanDiscard(ctx, tableID, userID)
}

// LookForGroupOptions is the resolver for the lookForGroupOptions field.
func (r *tableResolver) LookForGroupOptions(ctx context.Context, obj *model.Table) ([]*model.TableLookForGroupOption, error) {
	tableID, err := tableRoomIDFromObj(obj)
	if err != nil {
		return nil, err
	}
	return r.buildLookForGroupOptions(ctx, tableID)
}

// BackfillActive is the resolver for the backfillActive field.
func (r *tableResolver) BackfillActive(ctx context.Context, obj *model.Table) (bool, error) {
	tableID, err := tableRoomIDFromObj(obj)
	if err != nil {
		return false, err
	}
	_, active, err := r.tableFormingGaps(ctx, tableID)
	return active, err
}

// FormingGaps is the resolver for the formingGaps field.
func (r *tableResolver) FormingGaps(ctx context.Context, obj *model.Table) ([]*model.QueuePathGap, error) {
	tableID, err := tableRoomIDFromObj(obj)
	if err != nil {
		return nil, err
	}
	gaps, _, err := r.tableFormingGaps(ctx, tableID)
	return gaps, err
}

// User is the resolver for the user field.
func (r *tableSeatResolver) User(ctx context.Context, obj *model.TableSeat) (*model.User, error) {
	return obj.User, nil
}

// User is the resolver for the user field.
func (r *tableSeatSlotResolver) User(ctx context.Context, obj *model.TableSeatSlot) (*model.User, error) {
	return obj.User, nil
}

// MyTableSeat returns generated.MyTableSeatResolver implementation.
func (r *Resolver) MyTableSeat() generated.MyTableSeatResolver { return &myTableSeatResolver{r} }

// Table returns generated.TableResolver implementation.
func (r *Resolver) Table() generated.TableResolver { return &tableResolver{r} }

// TableSeat returns generated.TableSeatResolver implementation.
func (r *Resolver) TableSeat() generated.TableSeatResolver { return &tableSeatResolver{r} }

// TableSeatSlot returns generated.TableSeatSlotResolver implementation.
func (r *Resolver) TableSeatSlot() generated.TableSeatSlotResolver { return &tableSeatSlotResolver{r} }

type myTableSeatResolver struct{ *Resolver }
type tableResolver struct{ *Resolver }
type tableSeatResolver struct{ *Resolver }
type tableSeatSlotResolver struct{ *Resolver }
