package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/scruffyprodigy/playhub/graph/generated"
	"github.com/scruffyprodigy/playhub/graph/model"
	"github.com/scruffyprodigy/playhub/internal/auth"
)

// IsAdmin is the resolver for the isAdmin field.
func (r *userResolver) IsAdmin(ctx context.Context, obj *model.User) (bool, error) {
	if obj == nil || obj.Email == nil {
		return false, nil
	}
	return auth.IsAdminEmail(*obj.Email), nil
}

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
