apiVersion: v1
kind: ConfigMap
metadata:
  name: lobby-frontend-config
  namespace: playhub
  labels: { app: lobby-frontend }
data:
  REACT_APP_ENV: local
  REACT_APP_API_BASE_URL: "http://localhost:8081"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lobby-frontend
  namespace: playhub
  labels: { app: lobby-frontend }
spec:
  replicas: 1
  selector: { matchLabels: { app: lobby-frontend } }
  template:
    metadata:
      labels: { app: lobby-frontend }
    spec:
      containers:
        - name: frontend
          image: docker.io/scruffyprodigy/playhub-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: lobby-frontend-config
          readinessProbe:
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 3
          livenessProbe:
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 5
          resources:
            requests: { cpu: "100m", memory: "128Mi" }
            limits:   { cpu: "500m", memory: "512Mi" }
---
apiVersion: v1
kind: Service
metadata:
  name: lobby-frontend
  namespace: playhub
spec:
  selector: { app: lobby-frontend }
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
