apiVersion: v1
kind: Service
metadata:
  name: pg
  namespace: playhub
  labels:
    app: pg
spec:
  selector:
    app: pg
  ports:
    - name: pg
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pg
  namespace: playhub
spec:
  serviceName: pg
  replicas: 1
  selector:
    matchLabels:
      app: pg
  template:
    metadata:
      labels:
        app: pg
    spec:
      containers:
        - name: postgres
          image: postgres:16
          imagePullPolicy: IfNotPresent
          ports:
            - name: pg
              containerPort: 5432
          envFrom:
            - secretRef:
                name: pg-auth     # contains POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
            # Optional: mount your db-init config for first startup
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: init-sql
          configMap:
            name: db-init   # 👈 points to your k8s/init/db-init.yaml ConfigMap
  volumeClaimTemplates:
    - metadata:
        name: pgdata
        labels:
          app: pg
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
